### ISSUE TITLE
How to Register and Unregister?

### ISSUE THREAD

**Issue by kspearrin** [CrossGeeks/PushNotificationPlugin#1]
Hey guys,
I am coming from https://github.com/rdelrosario/xamarin-plugins/tree/master/PushNotification and looking to migrate over now that it is deprecated.

In reading over the docs I cannot find how we are suppose to actually invoke Register and Unregister? I see the event callbacks, but not an example of how to actually invoke registration.

Thanks.

**Comment by rdelrosario** [comment]
It registers automatically when you initialize

**Comment by kspearrin** [comment]
Can we add an option to handle that manually? Especially in the case of iOS we want to control when the prompt for enabling push notifications is presented to the user. The best practices for iOS are to ask for permissions (i.e. push notifications) when the user actually performs an action in the app that requires that permission. If our app just registers for push on the first time it is opened users will generally decline the permission (which is basically impossible to recover from on iOS unless you reinstall the app).

**Comment by rdelrosario** [comment]
In that case you can initialize disabling the autoregister flag by setting it as false on Initialize. And there are two static methods available to do that on demand on iOS:

PushNotificationManager.Register();
PushNotificationManager.Unregister();

**Comment by kspearrin** [comment]
Ok great. We'll check that out.

I'm not sure if it is different for FCM (we're on GCM now), but I know best practice for GCM was to unregister devices when a user logged out of the app (since notifications were no longer necessary then). Is unregistering devices ever necessary with FCM?

**Comment by rdelrosario** [comment]
The problem with FCM is that registration is done automatically. There is way to reset the token but not unregister.

On Android you can reset by using:

PushNotificationManager.Reset()

**Comment by rdelrosario** [comment]
Hi were you able to satisfy your needs with my comments here? To know if I can close this or let me know if need any help or assistance.

**Comment by kspearrin** [comment]
Yes, this can be closed for now.
