### ISSUE TITLE
CrossFirebasePushNotification.Current.UnsubscribeAll(); Not Working

### ISSUE THREAD

**Issue by djrpascu** [CrossGeeks/PushNotificationPlugin#103]
Plugin.FirebasePushNotification - v2.3.5
Xamarin.Forms - v3.5.0.169047
Physical Android Device - Google Pixel 2 (Android 9)

I try to do something below to setup some "DEV" topics for push notifications. I subscribe to a default list of topics, then switch to debug and attempt to unsubscribe from all topics before subscribing to debug set of default topics. It looks like CrossFirebasePushNotification.Current.SubscribedTopics is empty after calling UnsubscribeAll(), but when I send a notification to a topic that was supposedly cleared, it still receives it. If I clear the app from my device and deploy a new copy, it no longer sends to the old topic.

Reproduce by subscribing to a topic, run UnsubscribeAll(), and try sending a topic to FCM server.

`#if DEBUG`
`            CrossFirebasePushNotification.Current.UnsubscribeAll();`
`            DefaultTopics = new List<string>() { "debug_general", "debug_ilokano", "debug_english" };`
`#else`
`            DefaultTopics = new List<string>() { "general", "ilokano", "english" };`
`#endif`

**Comment by djrpascu** [comment]
Sorry, this should have been opened under:
https://github.com/CrossGeeks/FirebasePushNotificationPlugin

I think I found the issue. The Subscribe/Unsubscribe methods add/remove topics using the "Contains" method:
https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/31340236473c15d827a93ecacbb05ce57e38e0b0/src/Plugin.FirebasePushNotification.Android/FirebasePushNotificationManager.cs

Which means the topic names can't be substring of others and have to be unique. For example, you'll run into some quirks trying to use topics defined as "debug_general" and "general". Should probably use the "Equals" method instead. Workaround if using Nuget is to ensure your topics are unique. For example, "prod_general" and "debug_general".

**Comment by Flying-Light** [comment]
> Sorry, this should have been opened under: https://github.com/CrossGeeks/FirebasePushNotificationPlugin
> 
> I think I found the issue. The Subscribe/Unsubscribe methods add/remove topics using the "Contains" method: https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/31340236473c15d827a93ecacbb05ce57e38e0b0/src/Plugin.FirebasePushNotification.Android/FirebasePushNotificationManager.cs
> 
> Which means the topic names can't be substring of others and have to be unique. For example, you'll run into some quirks trying to use topics defined as "debug_general" and "general". Should probably use the "Equals" method instead. Workaround if using Nuget is to ensure your topics are unique. For example, "prod_general" and "debug_general".

Hello [djrpascu](https://github.com/djrpascu)
I know it is an old post, but I am facing the same problem now,
the "CrossFirebasePushNotification.Current.UnsubscribeAll();" is not working
I cannot clear them by one command,
the application keep receiving the old channels even aftaer calling "CrossFirebasePushNotification.Current.UnsubscribeAll();"
everything is up to date,

any suggestions?
