### ISSUE TITLE
Not compatible with Firebase.Messaging 60.1142.1

### ISSUE THREAD

**Issue by Lukas182** [CrossGeeks/PushNotificationPlugin#104]
Im getting this error when I try to install Plugin.PushNotification 1.3.0

Unable to find a version of 'Xamarin.Firebase.Messaging' that is compatible with 'Plugin.PushNotification 1.3.0 constraint: Xamarin.Firebase.Messaging (= 60.1142.0)'.

Thanks

**Comment by stefan89** [comment]
I have the same request. Could you update the Xamarin dependency libraries?

**Comment by alxbauer** [comment]
+1

**Comment by MRomeror** [comment]
+1

**Comment by rdelrosario** [comment]
Should be fixed in the latest version:

https://www.nuget.org/packages/Plugin.PushNotification/2.1.11
