### ISSUE TITLE
Always empty device token in Android

### ISSUE THREAD

**Issue by khadeeja-alif** [CrossGeeks/PushNotificationPlugin#108]
Empty device token on calling CrossPushNotification.Current.Token in Android.
I get the token randomly at times in Android debug. But in Release, I never get the device token.

**Comment by rahulinaction** [comment]
I am facing the same issue wherein the 
```PushNotificationManager.Initialize(this, true);``` returns a token whereas invoking it with a false flag work doesnt work in release. Anything particularly that I might be missing. It works fine in the sample application

**Comment by rdelrosario** [comment]
It seems the build number was not changed once you changed to build from Debug to Release. If it is incremented it triggers the registration token refresh.

The registration token may change when:

The app deletes Instance ID
The app is restored on a new device
The user uninstalls/reinstall the app
The user clears app data.
