### ISSUE TITLE
Exception while loading assemblies

### ISSUE THREAD

**Issue by Corstiaan84** [CrossGeeks/PushNotificationPlugin#11]
Hi,

I just added this package to a Xamarin.Forms solution, both the PCL and the Android projects.

The PCL builds fine but on build the Android project throws:

`System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.Compat'`

Wen I try to add this package it says

`Could not install package 'Xamarin.Android.Support.Compat 26.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

Any idea what this is about? I cleaned, rebuild, etc but it's not working...

**Comment by rdelrosario** [comment]
Do you have your Android support libraries updated from the Android SDK manager?

**Comment by Corstiaan84** [comment]
@rdelrosario Which ones do you mean exactly?

**Comment by rdelrosario** [comment]
Android support libraries

**Comment by rdelrosario** [comment]
Did you solve your issue?

**Comment by Corstiaan84** [comment]
Havent gotten to it yet. Working on some other stuff. Will let you know when I do. Thanks for checking in.

**Comment by rdelrosario** [comment]
Ok will close this for now. Please reopen if still have the issue.

**Comment by kaktusas2598** [comment]
Can this be reopened please?? I am having the same issue
