### ISSUE TITLE
Android push notification issue at the first time

### ISSUE THREAD

**Issue by yalamandarao** [CrossGeeks/PushNotificationPlugin#110]
Xamarin Forms
Currently I'm facing the issue in Android push notification at the first time.
Step to reproduce the issue:
step 1: I have installed the app into Android device.
step 2 : kill the app from the background mode.

After that I'm sending push notification by using some lib. But I'm not receiving the notification.

Step 3: Reopen the application and kill the app again.

Now I'm receiving the notification. But I just want to know why my android application is not getting notification at the first time.

Should I need add any extra in the Android code.

**Comment by rahulecomp** [comment]
Are you testing the application in debug mode. It would behave in the manner as you suggested. Please check the FAQ as it is listed overthere. It will work as expected when built from release mode
