### ISSUE TITLE
Push in IOs only show in foreground

### ISSUE THREAD

**Issue by sandybierhoff** [CrossGeeks/PushNotificationPlugin#111]
The push on IOs are only shown on the phone if the app is completely closed.
Debutanteando with the open app, gets to enter
CrossFirebasePushNotification.Current.OnNotificationReceived
but it is not shown on the phone.

I've already put this on AppDelegate.cs
FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.None;

Any idea what is happening ?

In android everything is fine

**Comment by sandybierhoff** [comment]
It worked, it seems I was dizzy. :) :)

Greetings

**Comment by ali-h2010** [comment]
I am not using Firebase but i am facing the same issue "Notification is shown only if the app is completely closed"
