### ISSUE TITLE
Android pushnotification not receiving when app is closed (Android version is 6.0)

### ISSUE THREAD

**Issue by parekh-vivek** [CrossGeeks/PushNotificationPlugin#112]
I am not getting notification when app is closed (Android version is 6.0)

So is it Android Version issue?

**Comment by rdelrosario** [comment]
Should check the https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/FAQ.md

There are certain scenarios were you won't receive it if the app is closed.
