### ISSUE TITLE
Update Nuget Xamarin.GooglePlayServices.Basement 

### ISSUE THREAD

**Issue by MRomeror** [CrossGeeks/PushNotificationPlugin#113]
I can't install this plugin.

Version conflict detected for Xamarin.GooglePlayServices.Basement. Install/reference Xamarin.GooglePlayServices.Basement 60.1142.1 directly to project MyProject.Android to resolve this issue. 
 MyProject.Android -> Xamarin.Forms.Maps 4.1.0.673156 -> Xamarin.GooglePlayServices.Maps 60.1142.1 -> Xamarin.GooglePlayServices.Basement (= 60.1142.1) 
 MyProject.Android -> MyProject -> Plugin.PushNotification 1.3.0 -> Xamarin.Firebase.Messaging 60.1142.0 -> Xamarin.GooglePlayServices.Basement (= 60.1142.0).

Can you update this dependencies?
Thanks

**Comment by rdelrosario** [comment]
Should be fixed in latest version:

https://www.nuget.org/packages/Plugin.PushNotification/2.1.11
