### ISSUE TITLE
On some Android device the event OnNotificationReceived not fired

### ISSUE THREAD

**Issue by NeedNap** [CrossGeeks/PushNotificationPlugin#114]
I used this plugin on my Xamarin Forms project for a long time and it worked fine.
After Android iOS update, on some devices (Huawei Smart Plus with Android 8, Huawei with Android 6, Samsung S6 with Android 7, ecc..), I never receive the OnNotificationReceived event when the app is in background or it's closed.

What can I do to solve this "big" problem?
Thank you

**Comment by rdelrosario** [comment]
Please check the FAQ section. There's situations where you won't get it in
this devices.

**Comment by NeedNap** [comment]
I followed all the instruction for the Android project setup and I read the FAQ section too, but I can't see nothing that helps me to solve the problem.
I tried the app in release mode (not debug) and the problem still persist.
Did you have any additional suggestion?
I have a close deadline to solve this issue for my project.
Thank you

**Comment by rdelrosario** [comment]
Hi 

Are you still having this issue?

**Comment by NeedNap** [comment]
Hi,
yes, I sill have this issue and I don't known how to solve it.
Do you have any suggestion about it?
Thanks

**Comment by rdelrosario** [comment]
How are you sending the payload?

**Comment by NeedNap** [comment]
This is a sample playload:


{
    "registration_ids": [
        "dCCxd4dZp4Q:APA91bHMoFpdn_FH2edXWpT10WJGSVuNq6rYu9cbXwFq8ntTpGqUeThy54S_38M6wYQex9Cw0-VegqgUO88iyDvhpy_sZxw0FtAa6yP2l1EmgJyoGduczm9iaHC-sttwnQSu4oHHn0He"
    ],
    "priority": "normal",
    "data": {
        "title": "Nuova news: ASTA ON-LINE ORNELLAIA VENDEMMIA D’ARTISTA 2016",
        "badge": 1,
        "custom": {
            "event_type": "NN",
            "post_id": 6938,
            "title": "ASTA ON-LINE <br/>ORNELLAIA VENDEMMIA D’ARTISTA 2016",
            "content": "Ha inizio oggi l'asta on-line dei grandi formati di Ornellaia Vendemmia d'Artista 2016. Per partecipare all'asta visita il sito <a href='http://www.sothebys.com/ornellaia'>www.sothebys.com/ornellaia</a>.",
            "post_type": "app-news",
            "brand": "",
            "post_date": "2019-08-29",
            "notification_title": "ASTA ON-LINE ORNELLAIA VENDEMMIA D’ARTISTA 2016"
        },
        "message": "Ha inizio oggi l'asta on-line dei grandi formati di Ornellaia Vendemmia d'Artista 2016. Per partecipare all'asta visita il sito <a href='http://www.sothebys.com/ornellaia'>www.sothebys.com/ornellaia</a>."
    },
    "notification": {
        "title": "Nuova news: ASTA ON-LINE ORNELLAIA VENDEMMIA D’ARTISTA 2016",
        "badge": 1,
        "custom": {
            "event_type": "NN",
            "post_id": 6938,
            "title": "ASTA ON-LINE <br/>ORNELLAIA VENDEMMIA D’ARTISTA 2016",
            "content": "Ha inizio oggi l'asta on-line dei grandi formati di Ornellaia Vendemmia d'Artista 2016. Per partecipare all'asta visita il sito <a href='http://www.sothebys.com/ornellaia'>www.sothebys.com/ornellaia</a>.",
            "post_type": "app-news",
            "brand": "",
            "post_date": "2019-08-29",
            "notification_title": "ASTA ON-LINE ORNELLAIA VENDEMMIA D’ARTISTA 2016"
        },
        "message": "Ha inizio oggi l'asta on-line dei grandi formati di Ornellaia Vendemmia d'Artista 2016. Per partecipare all'asta visita il sito <a href='http://www.sothebys.com/ornellaia'>www.sothebys.com/ornellaia</a>."
    },
    "time_to_live": 600
}

**Comment by rdelrosario** [comment]
Ok the problem seems you are sending a notification message in Android you
should send Data messages, as specified here:

https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/ReceivingNotifications.md

**Comment by NeedNap** [comment]
I changed the payload as the following:

{
    "registration_ids": [
        "dIeQo2wa1KM:APA91bEFXbHtbk36g6qlAuBO1jJxzkPj9Qf8akySnuAcGOE_ia0LRgcvwLUw-3DRnQkM_zkJd4yy74X9CHrNXh5utamIAB6F_oLVeV7xjLT8Uw1M6aYUf8wSptnbukmMMkfOB7p4bNjB"
    ],
    "priority": "normal",
    "data": {
        "title": "Nuova news: ASTA ON-LINE ORNELLAIA VENDEMMIA D’ARTISTA 2016",
        "badge": 2,
        "custom": {
            "event_type": "NN",
            "post_id": 6938,
            "title": "ASTA ON-LINE <br/>ORNELLAIA VENDEMMIA D’ARTISTA 2016",
            "content": "Ha inizio oggi l'asta on-line dei grandi formati di Ornellaia Vendemmia d'Artista 2016. Per partecipare all'asta visita il sito <a href='http://www.sothebys.com/ornellaia'>www.sothebys.com/ornellaia</a>.",
            "post_type": "app-news",
            "brand": "",
            "post_date": "2019-08-29",
            "notification_title": "ASTA ON-LINE ORNELLAIA VENDEMMIA D’ARTISTA 2016"
        },
        "message": "Ha inizio oggi l'asta on-line dei grandi formati di Ornellaia Vendemmia d'Artista 2016. Per partecipare all'asta visita il sito <a href='http://www.sothebys.com/ornellaia'>www.sothebys.com/ornellaia</a>."
    },
    "time_to_live": 600
}


As you can see I removed the "notification" node from the json but the OnNotificationReceived event never fired.

Where is the mistake?
Thank you a lot

**Comment by jpm-nz** [comment]
Did you get anywhere with this? Testing on Huawei phone and not receiving notifications when app is closed.

**Comment by rdelrosario** [comment]
This should be working fine on the latest version, If still having the issue please re-open or open a new issue.
