### ISSUE TITLE
Apple Push Notification Device Token- iOS 13

### ISSUE THREAD

**Issue by royaza** [CrossGeeks/PushNotificationPlugin#115]
iOS 13 changes the format of the push notification token:

// iOS 12
(deviceToken as NSData).description // "<965b251c 6cb1926d e3cb366f dfb16ddd e6b9086a 8a3cac9e 5f857679 376eab7C>"

// iOS 13
(deviceToken as NSData).description // "{length = 32, bytes = 0x965b251c 6cb1926d e3cb366f dfb16ddd ... 5f857679 376eab7c }"

More info here: https://nshipster.com/apns-device-tokens/

Therefore, it is needed to modify the token in the push registration step. 

As the PushNotificationPlugin converts the token to the string format, the app retrieves it as a string instead of NSData, it is not possible to convert it. 

Because I need to get it as NSData in order to modify it. 

Can you please update the package?

Otherwise, If you agree, I can commit the updated code.

thank you,

**Comment by Px7-941** [comment]
PR is on the way...

**Comment by michaeldimoudis** [comment]
I just submitted a PR to get device tokens when building your app against iOS 13 SDK https://github.com/CrossGeeks/PushNotificationPlugin/pull/117

Doesn’t look like this repo has been active for a while...? Nonetheless I wouldn’t wait for this PR to be merged, I copied this repo’s files in to my app and recommend that approach, as you might also encounter other issues with dependency version conflicts etc.

**Comment by royaza** [comment]
> I just submitted a PR to get device tokens when building your app against iOS 13 SDK #117
> 
> Doesn’t look like this repo has been active for a while...? Nonetheless I wouldn’t wait for this PR to be merged, I copied this repo’s files in to my app and recommend that approach, as you might also encounter other issues with dependency version conflicts etc.

Hi Michael, I finally changed my method of push in my project. I prefer to use native xamarin ios instead of open source library so it would be more convenient to update and modify. Thanks.

**Comment by michaeldimoudis** [comment]
> > I just submitted a PR to get device tokens when building your app against iOS 13 SDK #117
> > Doesn’t look like this repo has been active for a while...? Nonetheless I wouldn’t wait for this PR to be merged, I copied this repo’s files in to my app and recommend that approach, as you might also encounter other issues with dependency version conflicts etc.
> 
> Hi Michael, I finally changed my method of push in my project. I prefer to use native xamarin ios instead of open source library so it would be more convenient to update and modify. Thanks.

No problem. This is native Xamarin iOS code though... hopefully this PR is useful for others. It’s been working fine for me.

**Comment by rdelrosario** [comment]
Should be fixed in latest version:

https://www.nuget.org/packages/Plugin.PushNotification/2.1.11
