### ISSUE TITLE
Token generated for iOS is not valid

### ISSUE THREAD

**Issue by asafgo** [CrossGeeks/PushNotificationPlugin#119]
Token generated for iOS is not valid and short. it is working ok with https://github.com/CrossGeeks/FirebasePushNotificationPlugin

Example of generated string Token from RegisteredForRemoteNotifications method in AppDelegate.cs is "ea0ba15acba13fe735af10e4720425b60eec212975a03e959c430a967b07e12a"

Device is iPhone 6 with iOS version 12.4.2

**Comment by rdelrosario** [comment]
The firebase plugin uses FCM this one uses just APN that's why is different.
