### ISSUE TITLE
OnNotificationOpened is not working

### ISSUE THREAD

**Issue by gravitpt** [CrossGeeks/PushNotificationPlugin#12]
I implemented like the GIT, but when the App is in Background mode and I tapped a message, sent by Firebase, the App does not open. When the APP is running, i receive the message at the app normaly. 

I am using Xamarin Forms (Android).

Tks

**Comment by rdelrosario** [comment]
Can you put here your MainActivity class?

**Comment by rdelrosario** [comment]
Also do you have a SplashActivity?

**Comment by gravitpt** [comment]
My MainActivity
============

[Activity(Label = "GPSapp.Droid", Icon = "@drawable/icon", Theme = "@style/MyTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
		protected override void OnCreate(Bundle bundle)
		{
			base.OnCreate(bundle);

			Forms.Init(this, bundle);

            Xamarin.FormsMaps.Init(this, bundle);

            ToolbarResource = Resource.Layout.Toolbar;

            LoadApplication(new App());

			if (IsPlayServicesAvailable())
			{
				PushNotificationManager.ProcessIntent(Intent);
			}

		}

		public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
		{
			PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
		}

		public bool IsPlayServicesAvailable()
		{
			int resultCode = GoogleApiAvailability.Instance.IsGooglePlayServicesAvailable(this);
			if (resultCode != ConnectionResult.Success)
			{
				if (GoogleApiAvailability.Instance.IsUserResolvableError(resultCode))
                    Log.Debug("RegistrationIntentService", GoogleApiAvailability.Instance.GetErrorString(resultCode));
				else
				{
                    Log.Debug("RegistrationIntentService", "Sorry, this device is not supported");
					Finish();
				}
				return false;
			}
			else
			{
                Log.Info("RegistrationIntentService", "Google Play Services is available.");
				return true;
			}
		}
    }

**Comment by gravitpt** [comment]
CrossPushNotification.Current.OnNotificationOpened += (s, p) =>
			{

                  //  MainPage = new HomePage();

                System.Diagnostics.Debug.WriteLine("Opened");
				foreach (var data in p.Data)
				{
					System.Diagnostics.Debug.WriteLine($"{data.Key} : {data.Value}");
				}

				if (!string.IsNullOrEmpty(p.Identifier))
				{
					System.Diagnostics.Debug.WriteLine($"ActionId: {p.Identifier}");
				}

			};

**Comment by rdelrosario** [comment]
Ok I guess the problem might be the payload you are sending.

If you are sending it using firebase portal, plugin doesn't have any control of the ui. Because is a notification message, you should send data messages in order to be able to get messages. A more detailed explanation here:
https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/ReceivingNotifications.md

**Comment by carlasampaio01** [comment]
I just have this on iOS:

`  public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
                #if DEBUG
                            FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken, FirebaseTokenType.Sandbox);
                #endif
                #if RELEASE
                                    FirebasePushNotificationManager.DidRegisterRemoteNotifications(deviceToken,FirebaseTokenType.Production);
                #endif

        }

        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            FirebasePushNotificationManager.RemoteNotificationRegistrationFailed(error);

        }
        // To receive notifications in foregroung on iOS 9 and below.
        // To receive notifications in background in any iOS version
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            // If you are receiving a notification message while your app is in the background,
            // this callback will not be fired 'till the user taps on the notification launching the application.

            // If you disable method swizzling, you'll need to call this method. 
            // This lets FCM track message delivery and analytics, which is performed
            // automatically with method swizzling enabled.
            FirebasePushNotificationManager.DidReceiveMessage(userInfo);
            // Do your magic to handle the notification data
            System.Console.WriteLine(userInfo);
        }

        public override void OnActivated(UIApplication uiApplication)
        {
            FirebasePushNotificationManager.Connect();

        }
        public override void DidEnterBackground(UIApplication application)
        {
            // Use this method to release shared resources, save user data, invalidate timers and store the application state.
            // If your application supports background exection this method is called instead of WillTerminate when the user quits.
            FirebasePushNotificationManager.Disconnect();
        }
   `

**Comment by rdelrosario** [comment]
Will close this issue for now, if still having the issue feel free to reopen it.
