### ISSUE TITLE
ios13 apns-push-type

### ISSUE THREAD

**Issue by ionelmoisuc** [CrossGeeks/PushNotificationPlugin#123]
on ios 13, a payload like {aps:{content-available:1}} will not be delivered on devices unless apns-push-type is specified in the post header when sending the notification
details here: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
need this change implemented

**Comment by rdelrosario** [comment]
This is when sending the push notifications, the plugin is for receiving them doesn't handle sending it
