### ISSUE TITLE
 error: package com.google.firebase.messaging does not exist

### ISSUE THREAD

**Issue by WanftMoon** [CrossGeeks/PushNotificationPlugin#126]
An existing project stopped building after upgrading the nuget package. I created a clean one to see why, and just by adding the nuget pushnotification, the same build erros have shown.

error:
plugin.pushnotification error: package com.google.firebase.messaging does not exist

steps:

1. create new xamarin project (forms)
2. update nugets
3. add plugin.pushnotification.
4. build and error shows.

**Comment by KaranRami** [comment]
Adding Xamarin.Firebase.Messaging nuget separatly solved this issue for me.
