### ISSUE TITLE
Make OnReceived method virtual to Cancel Local Notification

### ISSUE THREAD

**Issue by JonathanQM** [CrossGeeks/PushNotificationPlugin#127]
Hi,

I think if making the DefaultPushNotificationHandler.OnReceived method virtual of each platform it would be enough, allowing to do a custom logic if necessary. Related #95 

in android something like...

```
...
        public override void OnReceived(IDictionary<string, object> parameters)
        {
            if (...)
            {
                parameters.Add("silent", true);
            }

            base.OnReceived(parameters);
        }
...
```

and ios

...
```
        public override void OnReceived(IDictionary<string, object> parameters)
        {
            if (...)
            {
		PushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.None;
            }
            else
            {
                PushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Badge;
            }

            base.OnReceived(parameters);
        }
```

**Comment by rdelrosario** [comment]
The latest version has improvements related to this, methods are now virtual. But also if the application is in foreground won't show notification unless "priority" set to "high" or "max" on the data payload.

**Comment by ali-h2010** [comment]
@rdelrosario, is there any way to override this behavior? I need the notifications to show regardless if app is i the foreground or background.
