### ISSUE TITLE
The executable was signed with invalid entitlements

### ISSUE THREAD

**Issue by rakeshkumar217** [CrossGeeks/PushNotificationPlugin#128]
Hello Team, I am not able to create ios build in release mode. Even i have added my phone's UDID in provisioning profile, enabled push notification under bundle identifier settings in apple account. 
Below is the error detail. 

Error: Your code signing/provisioning profiles are not correctly configured. Probably you have an entitlement not supported by your current provisioning profile, or your device is not part of the current provisioning profile. Please check the iOS Device Log for details (error: 0xe8008016)

Any solution to this problem.

Below is the screenshot of entitlement file:
![Screenshot 2020-01-14 at 7 30 33 PM](https://user-images.githubusercontent.com/11719126/72350476-83de4400-3704-11ea-9938-ad8f6e3296c2.png)

![Screenshot 2020-01-14 at 7 33 20 PM](https://user-images.githubusercontent.com/11719126/72350601-c1db6800-3704-11ea-9c53-b13ef33fbfda.png)

Thanks.

**Comment by rdelrosario** [comment]
This seems to be an issue related to your environment not the plugin
