### ISSUE TITLE
Importance of a channel

### ISSUE THREAD

**Issue by 78fede78** [CrossGeeks/PushNotificationPlugin#131]
how do you set the importance of a channel on high?

```
  if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                PushNotificationManager.DefaultNotificationChannelImportance = NotificationImportance.High;
                //Change for your default notification channel id here
                PushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

                //Change for your default notification channel name here
                PushNotificationManager.DefaultNotificationChannelName = "General";
            }
```

**'PushNotificationManager' does not contain a definition for 'DefaultNotificationChannelImportance'**

**Comment by rdelrosario** [comment]
What version are you using?

**Comment by 78fede78** [comment]
Plugin.PushNotification 2.1.18
because it is the latest version which support android 8.0

**Comment by rdelrosario** [comment]
Use the  **channel_id** key is set as the notification channel id if present will use that specified notification channel for this notification.

 Payload sample with channel id

```json
{
   "data" : {
     "title": "hello",
     "body": "firebase",
     "channel_id" : "PushNotificationChannel"

  }
}
```

**Comment by rdelrosario** [comment]
You can define the channel on the MainApplication and it will use this channel for the notification

**Comment by 78fede78** [comment]
ok but how can I not find that method? shouldn't I set importance on the channel?

**Comment by rdelrosario** [comment]
This is just on latest version not available on the one you are using.
