### ISSUE TITLE
Plugin Not Working with Android

### ISSUE THREAD

**Issue by KD2004** [CrossGeeks/PushNotificationPlugin#134]
Not working with android. Getting below error.  

CrossPushNotification.Current.OnNotificationReceived += (s, p) => {
// below error generated here. its only for android.
} //(Xamarin form)

**No compatible code running.
The selected debug engine does not support any code executing on the current thread (e.g. only native runtime code is executing)**

**Comment by rdelrosario** [comment]
This doesn't seem to be related to the plugin
