### ISSUE TITLE
Java.Lang.NullPointerException on PushNotificationManager.Initialize(this, true); on debug

### ISSUE THREAD

**Issue by JoacimWall** [CrossGeeks/PushNotificationPlugin#137]
Hi has followed your get started guide but get this,
 
Java.Lang.NullPointerException: 'Attempt to invoke virtual method 'void com.google.firebase.iid.FirebaseInstanceId.zzb(boolean)' on a null object reference'

We have upgrade from 6.xx version of xamarin.firebase.messages to 7.x

**Comment by remozwell** [comment]
did you fix the issue? i am having the same problem

**Comment by JoacimWall** [comment]
> did you fix the issue? i am having the same problem

Hi yes it's works but i don't remember what we did. 
the API has changed so I implement the ovverride OnNewToken and more
