### ISSUE TITLE
I do not receive notifications when the app is closed

### ISSUE THREAD

**Issue by fap0702** [CrossGeeks/PushNotificationPlugin#14]
I am developing a Xamarin.Forms app for Android. Apparently everything works very well, I can receive notifications when the app is open and when it is minimized, but when I close the process the app no longer allows me to receive notifications.

I understand an app has to generate a service in the background so that it can receive notifications in case it is closed, but I am not sure that this service is being created.

I await your prompt response.

**Comment by rdelrosario** [comment]
Hi 

Is not necessary to have a background service this is already handled if you initialize the plugin from an Android application class. How are you initializing now?

**Comment by fap0702** [comment]
app.xml.cs:

protected override void OnStart()
        {
            // Handle when your app starts
            CrossPushNotification.Current.OnTokenRefresh += (s, p) =>
            {
                Util.RegisterDevice(Device.RuntimePlatform, p.Token);
            };

            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                //string tipo = "";
                //string item = "";

                //foreach (KeyValuePair<string, object> data in p.Data)
                //{
                //    if (data.Key.Contains("tipo"))
                //        tipo = data.Value.ToString();
                //    if (data.Key.Contains("idItem"))
                //        item = data.Value.ToString();
                //}
                //Util.SaveDataNotification(tipo, item);
            };

            CrossPushNotification.Current.OnNotificationOpened += (s, p) =>
            {
                //string tipo = "";
                //string item = "";

                //foreach (KeyValuePair<string,object> data in p.Data)
                //{
                //    if (data.Key.Contains("tipo"))
                //        tipo =  data.Value.ToString();
                //    if (data.Key.Contains("idItem"))
                //        item = data.Value.ToString();
                //}
                //Util.SaveDataNotification(tipo, item);
            };
        }

MainActivity.cs:
[Activity(Label = "miProyecto.Droid", Icon = "@drawable/logo_ssangyong", Theme = "@style/MyTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation, ScreenOrientation = ScreenOrientation.Portrait)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            global::Xamarin.FormsMaps.Init(this, bundle);

            LoadApplication(new App());
            if (IsPlayServicesAvailable())
            {
                PushNotificationManager.ProcessIntent(Intent);
            }
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

        public bool IsPlayServicesAvailable()
        {
            int resultCode = GoogleApiAvailability.Instance.IsGooglePlayServicesAvailable(this);
            if (resultCode != ConnectionResult.Success)
            {
                if (GoogleApiAvailability.Instance.IsUserResolvableError(resultCode))
                    Log.Debug("RegistrationIntentService", GoogleApiAvailability.Instance.GetErrorString(resultCode));
                else
                {
                    Log.Debug("RegistrationIntentService", "Sorry, this device is not supported");
                    Finish();
                }
                return false;
            }
            else
            {
                Log.Info("RegistrationIntentService", "Google Play Services is available.");
                return true;
            }
        }
    }

MainAplication.cs: 

 [Application]
    public class MainApplication : Application //, Application.IActivityLifecycleCallbacks
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer)
          : base(handle, transer)
        {
        }

        public override void OnCreate()
        {
            base.OnCreate();
            //RegisterActivityLifecycleCallbacks(this);
            //A great place to initialize Xamarin.Insights and Dependency Services!
#if DEBUG
            PushNotificationManager.Initialize(this, true);
#else
            PushNotificationManager.Initialize(this, false);
#endif

            //Handle notification when app is closed here
            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                //string tipo = "";
                //string item = "";

                //foreach (KeyValuePair<string, object> data in p.Data)
                //{
                //    if (data.Key.Contains("tipo"))
                //        tipo = data.Value.ToString();
                //    if (data.Key.Contains("idItem"))
                //        item = data.Value.ToString();
                //}
                //Util.SaveDataNotification(tipo, item);
            };
        }

**Comment by rdelrosario** [comment]
Ok you see on MainApplication where has the comment:

 //Handle notification when app is closed here

Is where you handle the notifications when application is closed. A few things to consider if you are on a Xamarin Forms project:

- You cannot have any code that has xamarin forms dependencies or relays on it, because Xamarin Forms

**Comment by fap0702** [comment]
ok, if that handles the notifications when the app is closed, why do not you get any notification or is it missing me adding some code in this section?

**Comment by rdelrosario** [comment]
how are you sending the payload?

**Comment by fap0702** [comment]
this is what I am sending.

{"data":{"message":"hello","other_key":true,"body":"test"},"priority":"high","content_available":true,"registration_ids":["cAy-qbbNxzw:APA91bGbq7yiSeBt4sLucE6irUE8CseyJcEFM3BLNK80I8CixXMWrsF8XiCM73fuOfiegAYkxLjfP3s178WnNQohU9MjgJL7ooeeBZDzYXHSaDcz7-Yzbrdf2DGjv2WVI121DgAG5tEA"]}

**Comment by rdelrosario** [comment]
Did you check the FAQ:

https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/FAQ.md

There are a couple of reasons this could happen. Check number 3 and 4.

**Comment by fap0702** [comment]
Hello

apparently the problem was solved, today update Plugin.PushNotification to version 1.1.1, perform the corresponding tests and now it is working very well. I only happen with one device the same error and I guess it is for one of the reasons you mentioned above.

Thank you very much for your help.
