### ISSUE TITLE
Android still showing notification icon when app is on foreground

### ISSUE THREAD

**Issue by aucompany** [CrossGeeks/PushNotificationPlugin#16]
Android still showing notification icon when app is on foreground.
How to hide it, please?

**Comment by rdelrosario** [comment]
You mean you don't want to get the notification when app is foreground?

**Comment by rdelrosario** [comment]
Not exactly sure what you mean. But if what you want is just to show notification ui when in background then you could have a bool variable to indicate when is in foreground and if so you could do something like this:

```cs
  CrossPushNotification.Current.OnNotificationReceived += (s,p) =>
  {
        if(isForeground)
        {
             p.Data.Add("silent",true);
        }
    
        System.Diagnostics.Debug.WriteLine("Received");
    
  };
```

Let me know if this answers your question, if not feel free to reopen the issue.
