### ISSUE TITLE
Strange behaviour in IOS

### ISSUE THREAD

**Issue by rahulinaction** [CrossGeeks/PushNotificationPlugin#162]
I am getting a strange behaviour in IOS wherein I receieve messages when the app is in foreground but if I close the application I do not receive any messages when the app is in foreground. Is there a specific configuration which we need to do for foreground behaviour

**Comment by ali-h2010** [comment]
@rahulinaction  I am facing the same issue. When app is in foreground. i am not receiving any notifications. Only when the app is closed that i am getting the notification. I want it to show regardless.
