### ISSUE TITLE
IOS Show notification while application is in foreground

### ISSUE THREAD

**Issue by ahumeniy** [CrossGeeks/PushNotificationPlugin#17]
Is there a way to show the notification message even when the app is already opened? I checked the IPushNotificationHandler, but none of the methods fire or at least the debugger is not catching them.

**Comment by rdelrosario** [comment]
You can set UNNotificationPresentationOptions to get an alert, badge, sound when notification is received in foreground by setting static property **PushNotificationManager.CurrentNotificationPresentationOption**. By default is set to UNNotificationPresentationOptions.None.

```csharp
     public enum UNNotificationPresentationOptions
	 {
	 	 Alert,	//Display the notification as an alert, using the notification text.
		 Badge,	//Display the notification badge value in the application's badge.
		 None,	//No options are set.
		 Sound  //Play the notification sound.
	 }
```

Usage sample on iOS Project:

```csharp
   //To set for alert
   PushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert;

   //You can also combine them
   PushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Badge;
```

A good place to do this would be on the **OnReceived** method of a custom push notification handler if it changes depending on the notification, if not you can just set it once on the AppDelegate **FinishLaunching**.
