### ISSUE TITLE
Android 12 and missing android:exported attribute

### ISSUE THREAD

**Issue by bulente** [CrossGeeks/PushNotificationPlugin#175]
PNMessagingService doesn't contain the needed android:exported attribute to deploy to Android 12.

**Comment by hashem92** [comment]
Any idea how to fix it?

**Comment by pengham** [comment]
> PNMessagingService doesn't contain the needed android:exported attribute to deploy to Android 12.

Hi, manage to fix this problem?

**Comment by bulente** [comment]
The libraries must be changed to have a permanent solution. A temporary solution is changing the AndroidManifest.xml file generated at the obj folder and add the attributes there manually each time you build the solution.

**Comment by pengham** [comment]
> The libraries must be changed to have a permanent solution. A temporary solution is changing the AndroidManifest.xml file generated at the obj folder and add the attributes there manually each time you build the solution.

Agreed, just need to change PNMessagingService.android.cs line 9 from [Service] to [Service(Exported = true)]

**Comment by pengham** [comment]
Try the latest "Plugin.FirebasePushNotification" from CrossGeeks. This problem is solved.

**Comment by bulente** [comment]
Confirmed that the latest version is working

**Comment by bulente** [comment]
Upgrade your xamarin.forms and xamarin essentials references and also include latest Xamarin.Firebase.Messaging to your project and try again.

**Comment by hajuuk** [comment]
> Upgrade your xamarin.forms and xamarin essentials references and also include latest Xamarin.Firebase.Messaging to your project and try again.

Followed your instructions, same issue.

Updated demo app:
[App1.zip](https://github.com/CrossGeeks/PushNotificationPlugin/files/8697011/App1.zip)

Intermediate generated file (AndroidMainfest.xml)
[AndroidManifest.zip](https://github.com/CrossGeeks/PushNotificationPlugin/files/8697013/AndroidManifest.zip)

From the generated file,

'''
    <service android:name="crc640921eac73192168e.PNMessagingService">
      <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
    </service>
'''

This section still does not have export attribute.

I just noticed that, above plugin is different.
This repo refers to Plugin.PushNotification
But the above plugin is Plugin.**Firebase**PushNotification

**Comment by bulente** [comment]
Your solution doesn't give any error and builds successfully on Visual Studio 17.1.6 (archiving and creating APK files is also OK)

**Comment by hajuuk** [comment]
> Your solution doesn't give any error and builds successfully on Visual Studio 17.1.6 (archiving and creating APK files is also OK)

Oh, OK.

I'm running Visual Studio 2022, 17.2.0. I tried to use both Visual Studio to compile and MSBuild to compile, are given me the same error, java.exe error 1, msbuild provides more details, indicate android:export attribute.

Let me clear NuGet cache and try again.

**Comment by bulente** [comment]
Confirmed that 17.2.0 gives the error again. Try to build with 17.1.6 version of the studio.

**Comment by hajuuk** [comment]
> Confirmed that 17.2.0 gives the error again. Try to build with 17.1.6 version of the studio.

Probably add [Service(Exported = false)] attribute to [this file](https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/src/Plugin.PushNotification/PNMessagingService.android.cs) is the final solution.
Because I can't compile on my Mac compile server as well.

**Comment by bulente** [comment]
I dropped using this library and migrated to Plugin.FirebasePushNotification. Migration is easy and this library's last update time is long ago.

**Comment by hajuuk** [comment]
> I dropped using this library and migrated to Plugin.FirebasePushNotification. Migration is easy and this library's last update time is long ago.

Got it. Last question, is Plugin.FirebasePushNotification can use Apple Push Notification only? Or that only supports iOS devices 
 to use Firebase push notification.

**Comment by bulente** [comment]
It is using APN service at the background (you can't use any other service to send messages to ios devices) and works as a gateway service for iOS devices.
