### ISSUE TITLE
iOS 15.4.1 don't open push notification

### ISSUE THREAD

**Issue by pzavala26** [CrossGeeks/PushNotificationPlugin#176]
Working with a project:

Plugin.PushNotification: 3.6.9
iOS device: 15.4.1
Xamarin: 5.0.0.2196
VS: 2019 (16.11.13)

The App is already receiving push notifications, it's executing "CrossPushNotification.Current.OnNotificationReceived" OK, but when i tap to open de push notification nothing happen.. i put a breakpoint and a print in console but it's NOT executing "CrossPushNotification.Current.OnNotificationOpened"

**Comment by pengham** [comment]
I have a similar problem. I tapped push notification, OnNotificationOpened won't execute only when application in background.

Plugin.PushNotification: 3.6.9
iOS device: 15.4.1
Xamarin: 5.0.0.2401
VS: 2022 (17.1.6)

**Comment by pengham** [comment]
> Working with a project:
> 
> Plugin.PushNotification: 3.6.9 iOS device: 15.4.1 Xamarin: 5.0.0.2196 VS: 2019 (16.11.13)
> 
> The App is already receiving push notifications, it's executing "CrossPushNotification.Current.OnNotificationReceived" OK, but when i tap to open de push notification nothing happen.. i put a breakpoint and a print in console but it's NOT executing "CrossPushNotification.Current.OnNotificationOpened"

Hi, try the latest version of "Plugin.FirebasePushNotification" from CrossGeeks, it will solve your problem.
