### ISSUE TITLE
When to unscribe

### ISSUE THREAD

**Issue by opcodewriter** [CrossGeeks/PushNotificationPlugin#18]
I see the way it works is by subscribing to the singleton's event handler

`CrossPushNotification.Current.OnNotificationReceived +=`

but my question is, when should I unscribe?

**Comment by rdelrosario** [comment]
Is it a Xamarin Forms application?

**Comment by rdelrosario** [comment]
When to subscribe will depend on the use case of your application. For example, if you are using as a topic user email after they register, might make sense to subscribe after they are logged in. It varies depending on the app use case.

**Comment by rdelrosario** [comment]
Let me know if this answers your questions is not feel free to reopen the issue.
