### ISSUE TITLE
Custom Notification Visibility

### ISSUE THREAD

**Issue by Daraciel** [CrossGeeks/PushNotificationPlugin#20]
Hi,

I want to customize the way of notification its showing.

I mean, I want to "merge" notifications as other applications can (for example) or show a thumbail of an image.

Is there any option to "customize" the notification incoming after its showed in the status bar of the device?

Thank you

**Comment by rdelrosario** [comment]
This is the customization the plugin provides by default: 

https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/AndroidCustomization.md

But if you need to customize more than that you could implement your un PushNotificationHandler. Here more info:

https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/ReceivingNotifications.md#push-notification-handler

**Comment by Daraciel** [comment]
Thanks rdelrosario,

Your solution helps me a lot.

I thinks that i will write my custom notification handler because i want to be able to merge notifications.

I am making a chat application and it would be great if i could merge (as telegram do) notifications by emitter... but this is the final goal, there is a lot of features to implement before it.

Thank you very much

**Comment by rdelrosario** [comment]
Ok Great!

At some point I might I add some of those features to the plugin, hopefully in a few months
