### ISSUE TITLE
Android: tow different notifications with different id and tag cancel all

### ISSUE THREAD

**Issue by SinalyVector** [CrossGeeks/PushNotificationPlugin#21]
- package version **1.1.5**
- API  25+

When I receive tow different notifications with different **id** and **tag** and I click on one of them it cancel all

**Comment by rdelrosario** [comment]
How are you sending the payload?

**Comment by SinalyVector** [comment]
Thank you for responding so quickly.
I solved the problem.
For that, I changed several things in my code.
But I do not know which one solved the problem exactly.
First I removed the call of:
**FirebaseApp.InitializeApp (this);**

Then I changed the format of the message sent:
**At the beginning I sent:**
   "message":{
     "**data**": {
        "Id": "12345 ..."
        "Tag": ".... xxxxxx"
        ...................... etc ...
     }
    "registration_ids": ["xxxxxxxx" .....]
   }
}.

**Now I send:**
   "message":{
     "**notification**":{
       "Title": "xxxxxxxx"
       "Body": "yyyyyyyyyyyyyyyyyyy"
     }
     "**data**": {
        ........................
     }
    "registration_ids": ["xxxxxxxx" .....]
   }
}.
So I can close the bug.
Again, thank you very much
