### ISSUE TITLE
When two notifications with different ids, OnNotificationOpened only works in one - Android

### ISSUE THREAD

**Issue by SkillerSKL** [CrossGeeks/PushNotificationPlugin#23]
Hi, 
I'm trying to configure my app to receive two notifications. I receive but when open, only one the OnNotificationOpened get :s

**Comment by rdelrosario** [comment]
When you tap on the other one you don't get the event fired? If you tap on each you receive each corresponding notification event?

**Comment by SkillerSKL** [comment]
When you tap on the other one you don't get the event fired?
- No. I'm debugging and don't fired.

If you tap on each you receive each corresponding notification event?
- I configured to open a page when tap a notification. The first is opening but the other no. 

Obs: This happens only when two notifications are displayed. If i receive one and tap, open normally.

**Comment by rdelrosario** [comment]
Fixed in latest version 1.3.0.
