### ISSUE TITLE
Can't receive push notifications in ios 11

### ISSUE THREAD

**Issue by RagulChandra** [CrossGeeks/PushNotificationPlugin#25]
Can't receive push notifications in ios 11.Do i need to add GoogleService-Info.plist?

**Comment by rdelrosario** [comment]
Yes need to add your  plist as the docs specifies

**Comment by rdelrosario** [comment]
Wait are you using firebase on ios or not?

**Comment by rdelrosario** [comment]
Not sure what's the issue here, please open a new ticket with more details
