### ISSUE TITLE
When App is closed, OnNotificationOpened not working

### ISSUE THREAD

**Issue by SkillerSKL** [CrossGeeks/PushNotificationPlugin#26]
If App is open, OnNotificationOpened works, but if app is closed, i click in notification and only load the app main page. I'm using xamarin forms.

Help me!

**Comment by rdelrosario** [comment]
You need to navigate to the page you want once you receive the OnNotificationOpened event

**Comment by rdelrosario** [comment]
Also where do you have the OnNotificationOpened event?

**Comment by SkillerSKL** [comment]
I have OnNotificationOpened event in App.xaml.cs in method OnStart. This method is implemented the navigation.  But i want to implement to working in MainApplication too. Sorry for english.

**Comment by rdelrosario** [comment]
Why you want to implement it on mainapplication?

**Comment by SkillerSKL** [comment]
Because when app is closed, the OnNotificationOpened event not working. What do i do for the event working with app closed?

**Comment by rdelrosario** [comment]
OnNofiticationOpened should work just fine when application closed, did you call ProcessIntent on MainActivity OnCreate method and on OnNewIntent method

**Comment by SkillerSKL** [comment]
My MaincActivity:

 [Activity(Label = "MusicScopeApp", Icon = "@drawable/icon", Theme = "@style/MainTheme", MainLauncher = false, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            DependencyService.Register<ToastNotification>();
            ToastNotification.Init(this, new PlatformOptions() { SmallIconDrawable = Android.Resource.Drawable.IcDialogInfo });
            IconControls.Init(Resource.Id.toolbar, Resource.Id.tabs);
            FormsAppCompatActivity.ToolbarResource = Resource.Layout.toolbar;
            FormsAppCompatActivity.TabLayoutResource = Resource.Layout.tabs;
            FlowListView.Init();
            CachedImageRenderer.Init();
            UserDialogs.Init(this);
            PushNotificationManager.ProcessIntent(Intent);
            LoadApplication(new App());
        }

        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            PushNotificationManager.ProcessIntent(intent);
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

        protected override void OnActivityResult(int requestCode, Android.App.Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            InAppBillingImplementation.HandleActivityResult(requestCode, resultCode, data);
        }


    }

**Comment by SkillerSKL** [comment]
I have a SplashActivity. It's here:


    [Activity(Theme = "@style/Theme.Splash",
              MainLauncher = true,
              NoHistory = true)]
    public class SplashActivity : Activity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Create your application here
            StartActivity(typeof(MainActivity));
        }
    }

**Comment by SkillerSKL** [comment]
Is it right?

**Comment by rdelrosario** [comment]
On your splash activity OnCreate try doing this:

  // Create your application here
            var mainIntent = new Intent(Application.Context, typeof(MainActivity));

            if (Intent.Extras != null)
            {
                mainIntent.PutExtras(Intent.Extras);
            }
            mainIntent.SetFlags(ActivityFlags.SingleTop);

            StartActivity(mainIntent);

**Comment by rdelrosario** [comment]
@SkillerSKL  Let me know if this worked for you.

**Comment by SkillerSKL** [comment]
Hi @rdelrosario,
Sorry for delay. Your solution didn't work  :s

When tap in notiication open only a mainactivity but the event opened not fired.

**Comment by KGSachinthaU** [comment]
Hi,
I have same problem,
help me !

**Comment by simon25608** [comment]
Hi!

I have the same problem.

My version of xamarin is 2.5.0.77107 and I'm testing it in a sansung s7.

**Comment by rdelrosario** [comment]
Try using:

https://www.nuget.org/packages/Plugin.PushNotification/1.2.0-beta

**Comment by simon25608** [comment]
PushNotificationManager does not exist in the current context in MainActivity. 
I have de using Plugin.PushNotification;

**Comment by rdelrosario** [comment]
Did you check if Plugin.PushNotification is installed on the Android project references?

**Comment by simon25608** [comment]
Yes, I have the latest version installed on all projects, as you can see in the attached image.

![2018-01-18_225301](https://user-images.githubusercontent.com/18722357/35123525-d1bbcb46-fca2-11e7-9f62-e147cc2b56a8.jpg)

It's normal when upgrading to the latest version if you uninstall the libraries you see in the other capture?

![2018-01-18_224737](https://user-images.githubusercontent.com/18722357/35123526-d1dbce1e-fca2-11e7-84e7-7dadae3e45f9.jpg)

**Comment by rdelrosario** [comment]
Hi guys are you still having issues?

I just released a new stable version of the plugin:

https://www.nuget.org/packages/Plugin.PushNotification/1.2.2

**Comment by simon25608** [comment]
I continue with the same problem:
**PushNotificationManager does not exist in the current context**
The same thing also happens to me in the latest version of FirebasePushNotificationPlugin :(

**Comment by rdelrosario** [comment]
Where are you trying to use this class? It only exists on Android and iOS projects not PCL

**Comment by simon25608** [comment]
I use it only on Android and IOS projects.

Enclosed here is a classes view of the Android project:
![img_23012018_164406_0](https://user-images.githubusercontent.com/18722357/35286083-4c53af3a-005f-11e8-95a1-8a1f22e6cfbc.png)

As you can see, the PushNotificationManager class is missing :(

**Comment by rdelrosario** [comment]
I think this issue is in your environment. If you check the sample this doesn't happen it compiles correctly.

**Comment by simon25608** [comment]
I've created an empty project with prism and this plugin and it's the same thing. :(

Did you try it?Will the nuget package be well generated?

**Comment by rdelrosario** [comment]
Yes I tried the sample on this repo FirebasePushSample and compiles and works fine on Android and iOS.

**Comment by SkillerSKL** [comment]
OnNotificationOpened not working here yet. @rdelrosario , do you have any sample with this method working with app closed ?

**Comment by rdelrosario** [comment]
The sample in the repo OnNotificationOpened works when app is closed.

**Comment by simon25608** [comment]
> Yes I tried the sample on this repo FirebasePushSample and compiles and works fine on Android and iOS.

The example project works perfectly well for me, however upgrading from a previous version does not.

I have this problem on several pcs and it seems that there are more problems like mine.

**Comment by rdelrosario** [comment]
I updated the plugin, let me know if still have issues with this.

If still have issues I would suggest first uninstall your current plugin version and then install the last one. Also confirm dependencies have the right version installed.

**Comment by SkillerSKL** [comment]
Thanks @rdelrosario.
I followed the sample FirebasePushSample and worked!!

**Comment by asanka-indrajith** [comment]
So to understand this. FirebasePushNotificationPlugin works when app is closed not this PushNotificationPlugin? Is it?

**Comment by fm698** [comment]
> 
> 
> On your splash activity OnCreate try doing this:
> 
> ```cs
> [Activity(Theme = "@style/Theme.Splash",
>           MainLauncher = true,
>           NoHistory = true)]
> public class SplashActivity : Activity
> {
>     protected override void OnCreate(Bundle savedInstanceState)
>     {
>         base.OnCreate(savedInstanceState);
> 
>         // Create your application here
>             var mainIntent = new Intent(Application.Context, typeof(MainActivity));
> 
>             if (Intent.Extras != null)
>             {
>                 mainIntent.PutExtras(Intent.Extras);
>             }
>             mainIntent.SetFlags(ActivityFlags.SingleTop);
> 
>             StartActivity(mainIntent);
>     }
> }
> ```

Thank you, this solution 

> 
> 
> On your splash activity OnCreate try doing this:
> 
> ```cs
> [Activity(Theme = "@style/Theme.Splash",
>           MainLauncher = true,
>           NoHistory = true)]
> public class SplashActivity : Activity
> {
>     protected override void OnCreate(Bundle savedInstanceState)
>     {
>         base.OnCreate(savedInstanceState);
> 
>         // Create your application here
>             var mainIntent = new Intent(Application.Context, typeof(MainActivity));
> 
>             if (Intent.Extras != null)
>             {
>                 mainIntent.PutExtras(Intent.Extras);
>             }
>             mainIntent.SetFlags(ActivityFlags.SingleTop);
> 
>             StartActivity(mainIntent);
>     }
> }
> ```

Thank you, this fixed my problem, but anyone who will try this solution, please note that if you ovverided OnResume, but this code inside onresume method
