### ISSUE TITLE
Unable to install into Xamarin Android project targeting android 8

### ISSUE THREAD

**Issue by vsdotnetguy** [CrossGeeks/PushNotificationPlugin#27]
We're trying to use ver 1.1.5 of your plugin.  However, we can't get it to install as we're targeting Android 8.  When we try to install within the Android project it starts to install the dependencies but then when it hits the Xamarin.GooglePlayServices.Basement pkg, it immediately stops and rolls back the install. Is it because the dependency should be for Xamarin.GooglePlayServices.Base vs .Basement?

Below is log:
Attempting to gather dependency information for package 'Plugin.PushNotification.1.1.5' with respect to project 'MobileApp.UI.Android', targeting 'MonoAndroid,Version=v8.0'
Gathering dependency information took 10.02 min
Attempting to resolve dependencies for package 'Plugin.PushNotification.1.1.5' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Plugin.PushNotification.1.1.5'
Resolved actions to install package 'Plugin.PushNotification.1.1.5'
Found package 'Plugin.PushNotification 1.1.5' in 'C:\dev\TAFS\MobileApp\packages'.
Retrieving package 'Xamarin.Firebase.Common 60.1142.0' from 'nuget.org'.
Retrieving package 'Xamarin.Firebase.Iid 60.1142.0' from 'nuget.org'.
Retrieving package 'Xamarin.Firebase.Messaging 60.1142.0' from 'nuget.org'.
Retrieving package 'Xamarin.GooglePlayServices.Base 60.1142.0' from 'nuget.org'.
Retrieving package 'Xamarin.GooglePlayServices.Tasks 60.1142.0' from 'nuget.org'.
Adding package 'Xamarin.GooglePlayServices.Tasks.60.1142.0' to folder 'C:\dev\TAFS\MobileApp\packages'
Added package 'Xamarin.GooglePlayServices.Tasks.60.1142.0' to folder 'C:\dev\TAFS\MobileApp\packages'
Added package 'Xamarin.GooglePlayServices.Tasks.60.1142.0' to 'packages.config'
Successfully installed 'Xamarin.GooglePlayServices.Tasks 60.1142.0' to MobileApp.UI.Android
Adding package 'Xamarin.Firebase.Common.60.1142.0' to folder 'C:\dev\TAFS\MobileApp\packages'
Added package 'Xamarin.Firebase.Common.60.1142.0' to folder 'C:\dev\TAFS\MobileApp\packages'
Install failed. Rolling back...
Package 'Xamarin.Firebase.Common.60.1142.0 : Xamarin.GooglePlayServices.Basement [60.1142.0, 60.1142.0], Xamarin.GooglePlayServices.Tasks [60.1142.0, 60.1142.0]' does not exist in project 'MobileApp.UI.Android'
Removed package 'Xamarin.GooglePlayServices.Tasks.60.1142.0 : Xamarin.GooglePlayServices.Basement [60.1142.0, 60.1142.0]' from 'packages.config'
Removing package 'Xamarin.Firebase.Common.60.1142.0 : Xamarin.GooglePlayServices.Basement [60.1142.0, 60.1142.0], Xamarin.GooglePlayServices.Tasks [60.1142.0, 60.1142.0]' from folder 'C:\dev\TAFS\MobileApp\packages'
Removed package 'Xamarin.Firebase.Common.60.1142.0 : Xamarin.GooglePlayServices.Basement [60.1142.0, 60.1142.0], Xamarin.GooglePlayServices.Tasks [60.1142.0, 60.1142.0]' from folder 'C:\dev\TAFS\MobileApp\packages'
Removing package 'Xamarin.GooglePlayServices.Tasks.60.1142.0 : Xamarin.GooglePlayServices.Basement [60.1142.0, 60.1142.0]' from folder 'C:\dev\TAFS\MobileApp\packages'
Removed package 'Xamarin.GooglePlayServices.Tasks.60.1142.0 : Xamarin.GooglePlayServices.Basement [60.1142.0, 60.1142.0]' from folder 'C:\dev\TAFS\MobileApp\packages'
Executing nuget actions took 1.2 min
This collection is read-only.
Time Elapsed: 00:11:13.3780246
========== Finished ==========

**Comment by rdelrosario** [comment]
Preview support to android o comming this week

**Comment by rdelrosario** [comment]
Please let me know if this solved your issue

**Comment by rdelrosario** [comment]
Reopen this issue or create a new one if this doesn't fix your issue.
