### ISSUE TITLE
Notification doesn't show in background when targeting API 26

### ISSUE THREAD

**Issue by BradleyAlcock** [CrossGeeks/PushNotificationPlugin#28]
When the app receives a notification in the background, I don't receive notifications.
I do receive this warning:
Notification: Use of stream types is deprecated for operations other than volume control

Everything works perfectly when targeting API 25. doing a few quick searches, it seems there's a deprecation on NotificationCompat.Builder(Context)
and this has changed to NotificationCompat.Builder(Context, String)

Is there an additional step I need to do to get this working?

Source:
https://forums.bignerdranch.com/t/no-notifications-in-oreo/13160
https://stackoverflow.com/questions/45395669/notifications-fail-to-display-in-android-oreo-api-26

**Comment by rdelrosario** [comment]
Preview support comming this week

**Comment by rdelrosario** [comment]
Please let me know if this solved your issue

**Comment by BradleyAlcock** [comment]
Notifications were received after changing target to API 26, running on a pixel with API 26.
Issue resolved, thank you
