### ISSUE TITLE
Registration ID

### ISSUE THREAD

**Issue by SarahCoates1** [CrossGeeks/PushNotificationPlugin#29]
Hi.
I have set up the code to receive notifications in my xamarin forms app (in the Android project).  I have tested this by sending a notification from my Firebase account.
I see that when sending a notification from code that we require the registration id.  How do we get the registration id please?  Out of interest, is registration id mandatoty, or can we send to all registered devices?
Thanks

**Comment by rdelrosario** [comment]
You can get the registration id on event:

```csharp

  CrossPushNotification.Current.OnTokenRefresh += (s,p) =>
  {
        System.Diagnostics.Debug.WriteLine($"TOKEN : {p.Token}");
  };

```

You can send to all registered devices by sending all ids in an array.

Is not mandatory to send notifications using registration id, you can use topics too.

**Comment by SarahCoates1** [comment]
Thanks rdelrosario, I hadn't realised that the token was referring to the registration id.  That worked great.  How would we go about using topics please?  Thanks for the great Nuget!

**Comment by rdelrosario** [comment]
If you want to use all firebase features will recommend using this plugin instead https://github.com/CrossGeeks/FirebasePushNotificationPlugin which has topics support
