### ISSUE TITLE
IOS and Azure Notification Hub

### ISSUE THREAD

**Issue by SarahCoates1** [CrossGeeks/PushNotificationPlugin#30]
Hi.  We have been sending our notifications with the Azure Notification Hub up until now.  We are now trying out your Nuget as it covers both Android and IOS.  Can we still use the Azure Notification Hub to send the Apple APNS Notifications and to receive them using your nuget and the code provided?  I have my receiving code working (tested using Pusher) and am now looking at the best way to Send.
Many thanks

**Comment by rdelrosario** [comment]
Yes you can use azure notification hubs with this plugin but need to integrate the xamarin notification hub nuget package on both platform and register the tags once you get the token
