### ISSUE TITLE
Push Notification not working correctly

### ISSUE THREAD

**Issue by KGSachinthaU** [CrossGeeks/PushNotificationPlugin#31]
Hi, 
I using yours PushNotificationPlugin for my application, but It`s not working correctly,

1. When I configured code in MainApplication.cs (All configurations done according to sample project your guys  provided )..... pushNotification not receiving, because of device token all ways empty string 
//MainApplication.cs
   [Application]
    public class MainApplication : Application
    {
        public MainApplication(IntPtr handle, JniHandleOwnership transer) : base(handle, transer)
        {
            
        }

        public override void OnCreate()
        {
            base.OnCreate();

#if DEBUG
            PushNotificationManager.Initialize(this, true);
#else
            PushNotificationManager.Initialize(this,false);
#endif
            //Set the activity type that will handle your notifications
            PushNotificationManager.NotificationActivityType = typeof(MainActivity);

            CrossPushNotification.Current.OnNotificationOpened += (s, p) =>
            {
                //Log.Debug(TAG, "OPENED");

                foreach (var data in p.Data)
                {
                    if (data.Key == "promoId")
                    {
                        if (data.Value != null)
                        {
                            //Log.Debug(TAG, "PromoID::" + data.Value.ToString());
                            PushNotificationToken.PromoId = data.Value.ToString();
                        }
                        else
                        {
                            PushNotificationToken.PromoId = null;
                        }
                    }
                }
            };
        }
    }

//App.cs in main project
all done for OnStart() method

//MainActivity.cs end of the onCreate method like below
       protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            //rest code 
            LoadApplication(new App());
            PushNotificationManager.ProcessIntent(Intent);
        }
        
        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            PushNotificationManager.ProcessIntent(intent);
        }

------------------------------------------------------------------------------------------------
        

2. When I configured code in MainActivity.cs PushNotification receiving both background and foreground, but in both natures not trigger OnNotificationOpened event.

**Comment by rdelrosario** [comment]
What device and os version are you testing on?

**Comment by KGSachinthaU** [comment]
I used huawei mobile phone, Now push notification is working fine, This is amazing plugin thanks guys.
