### ISSUE TITLE
Push Notification not working (API 26)

### ISSUE THREAD

**Issue by javilopezruiz** [CrossGeeks/PushNotificationPlugin#35]
I am testing push notifications on a Xiaomi Mi A1 with Android 8.0 and push notifications are not received when app is opened, in foreground. 

If app is killed everything ok.

**Comment by rdelrosario** [comment]
Did you added notification channels?

**Comment by javilopezruiz** [comment]
I don't know what you mean. Could you explain what should I do to see the notifications if the app is in foreground in Android?

**Comment by rdelrosario** [comment]
What version did you install?

**Comment by rdelrosario** [comment]
Please try installing this version:

https://www.nuget.org/packages/Plugin.PushNotification/1.2.2

If doesn't fix the issue feel free to reopen this issue or create a new one.
