### ISSUE TITLE
Unstable on background

### ISSUE THREAD

**Issue by fabricyo** [CrossGeeks/PushNotificationPlugin#4]
Hi, I'm getting a few problems with the notifications.
The trouble is:
I have installed on a few devices, is something like production environment where I use here at my work.
Well, at one of the devices (Samsung J5) the app receives all the notifications that I send thru my website.
My cellphone (Samsung J7) doesn't receive all of the notifications, just sometimes, even when I open the app, it doesn't give the notifications that I've 'missed'.
And a third device (Samsung Duos) never received notifications.

I'm quite new on mobile dev, so I don't know what look, maybe is something about background services.

Well, thanks in advance!
Sorry for English.

**Comment by rdelrosario** [comment]
Did you check the FAQ section for possible causes?

https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/FAQ.md

**Comment by fabricyo** [comment]
Yes I did.

**Comment by rdelrosario** [comment]
Not sure if this helps:

https://android.stackexchange.com/questions/135222/samsung-galaxy-a3-block-all-notifications-except-email-and-sms

**Comment by fabricyo** [comment]
No I don't have this issue.
See, if I restart my phone and don't open the app or I don't open it after some hours, it doesn't popup any notification.

**Comment by rdelrosario** [comment]
Did you try that on a Release apk ?

**Comment by fabricyo** [comment]
Yes, with the signed and with the other.
But maybe I'm misunderstanding the FAQ, you mention about initialize in the android project, could you talk a little more?

**Comment by rdelrosario** [comment]
Are you still having this issue?

Also how are you sending the payload?

**Comment by rdelrosario** [comment]
Will close this issue for now if still have problems just open a new issue or reopen this one.

**Comment by fabricyo** [comment]
Hey, I'm back, sorry, this week has been quite busy for me.
Well, yes, this issue is still happening.
I'm sending my payload like this:
`my void method ()
{
    var ServerApiKey = "mykey";
    FCMClient client = new FCMClient(ServerApiKey);
    var message = new Message()
        {
           To = "/topics/android",
           Notification = new AndroidNotification()
           {
               Title = "Novo serviço",
               Body = "Abra o app para visualizar",
               Sound = "default"
            }
         };
     var result = client.SendMessageAsync(message);
}`//end of my method

And I'm using FirebaseNet.Messaging.
Could you think what is causing this bug?
