### ISSUE TITLE
Only the first push message is received

### ISSUE THREAD

**Issue by bda2206** [CrossGeeks/PushNotificationPlugin#41]
Hi,
just upgraded from the old push component. Like this ones implementation, much cleaner thanks.

My problem is that the first push message is handled by the application (ie. shows in the logs, and I manually do a notification using a toast component as the messages are data that needs interpreting. ), then the following messages seem to bypass the application (not in the logs at all) and just pop up the toast outside the app. It is the active application, in debug mode.. Have tried with debugger attached and not attached. Same results.

using IOS - latest, followed the example. 

help? thanks :)

hmm, I think there's a variation in the data I'm sending in the push, as they are generated from 2 different manners.

**Comment by rdelrosario** [comment]
Hi

You mean you want to display your own custom alert each time?

**Comment by bda2206** [comment]
i’m trying to feed data to the game and then put up an alert that has
processed the data. but the message doesn’t hit my app, just the device.
tried with app foreground and background, nothing !

**Comment by rdelrosario** [comment]
I guess what you want is to get a silent notification. On iOS by default notification is received once you tap the notification not before.

On iOS to get a silent notification you should send "content_available" : 1 inside the "aps" payload key.

**Comment by rdelrosario** [comment]
{"aps":{"content-available":1}}

When you sent content-available key you will get the notification immediately on your app

**Comment by bda2206** [comment]
thanks boss. I've gone back to the platform dev to see how I can do that
with their offering.

**Comment by rdelrosario** [comment]
Let me know if you get to solve your issue

**Comment by rdelrosario** [comment]
Will close this for now if still have any issue just open a new one.

**Comment by bda2206** [comment]
thanks. i’m in discussion with 3rd party regarding not having full aps
options available in their framework
