### ISSUE TITLE
message received but OnNotificationReceived didnt run

### ISSUE THREAD

**Issue by msdYqb** [CrossGeeks/PushNotificationPlugin#42]
hello there,

when app is closed message is received in the device
but OnNotificationReceived didn't update the badge
//in MainApplication
//Handle notification when app is closed here
            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                CrossBadge.Current.SetBadge(5);
            };
the code above works fine in foreground and background not when app is killed
any solution for this please
thanks

**Comment by rdelrosario** [comment]
Did you check the FAQ section?

**Comment by msdYqb** [comment]
yes i did, one thing to note is I don't find Android Support Library in 
android SDK Manager

**Comment by rdelrosario** [comment]
What phone are you testing on?

**Comment by msdYqb** [comment]
Samsung SM-J510F

**Comment by rdelrosario** [comment]
Are you debugging when you kill the app?

**Comment by rdelrosario** [comment]
You won't receive any push notifications if application is stopped while debugging, should reopen and close again for notifications to work when app closed. This is due to the application being on an unstable state when stopped while debugging.

**Comment by msdYqb** [comment]
no I'm not debugging I've tried it with release build

**Comment by msdYqb** [comment]
IT WORKS! turn out the problem is with the CrossBadge Plugin!
ive tried this 

            //Handle notification when app is closed here
            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                string libraryPath = System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal); ;
                var path = Path.Combine(libraryPath, "test.txt");
                File.WriteAllText(path, "testing");
            };
and it works as the file actually created with testing value 
Thanks !
