### ISSUE TITLE
Shows only one notification at a time

### ISSUE THREAD

**Issue by SkillerSKL** [CrossGeeks/PushNotificationPlugin#43]
Hi, 
How do I do to display multiples notifications? Currently, one notification replace another.
 
My payload:

 var message = new Message
                    {                                               
                        Data = new
                        {
                            title = "xxxxxx",
                            message = description,
                            Id = new Guid().ToString(),                            
                            parameter = parameter,
                            type = notification,
                            typeGallery = typeGallery
                        },
                        RegistrationIds = tokensUser,
                    };

**Comment by rdelrosario** [comment]
Id must be an int

**Comment by SkillerSKL** [comment]
Thanks. I changed, but yet it is replacing :s

**Comment by rdelrosario** [comment]
You are sending  a different id each time?

**Comment by rdelrosario** [comment]
mmm try adding a Tag

**Comment by SkillerSKL** [comment]
Thanks again @rdelrosario. 
I did twice changes, i inserted a tag as you said and put o Id in lowercase.
