### ISSUE TITLE
Register()

### ISSUE THREAD

**Issue by edmckee** [CrossGeeks/PushNotificationPlugin#45]
I'm using a xamarin forms app.  I need to delay the registration of push notifications until after I receive user credentials. 
I see how to initialize with the auto register but don't see a way to call the register from the shared .cs 

Do you have an example on calling the register when not auto registering?

**Comment by rdelrosario** [comment]
This will be included on next oficial release

**Comment by rdelrosario** [comment]
Released in latest version 1.3.0. Included methods for registration/unregistration on demand if needed:
```cs
CrossPushNotification.Current.RegisterForPushNotifications();
CrossPushNotification.Current.UnegisterForPushNotifications();
```

**Comment by edmckee** [comment]
That's fantastic.  Thank You!!!

**Comment by JoshDiDuca** [comment]
Unhandled Exception:

`System.MissingMethodException: Method 'Plugin.FirebasePushNotification.Abstractions.IFirebasePushNotification.RegisterForPushNotifications' not found.`

**Comment by rdelrosario** [comment]
@JoshDiDuca What platform?

**Comment by JoshDiDuca** [comment]
@rdelrosario Android with 1.3.0, haven't tested on iOS.

**Comment by rdelrosario** [comment]
@JoshDiDuca I think you installed the incorrect plugin on one of the projects. the exception is about https://github.com/CrossGeeks/FirebasePushNotificationPlugin not this plugin.

**Comment by JoshDiDuca** [comment]
@rdelrosario Apologies, that may have been my fault, I probably had both of them installed at one point but ended up not using either of the two plugins due to the fact that the token was always empty, never called the refresh token event either. 

I've since added push notifications using a completely different solution.

Thanks, I appreciate it.

**Comment by rdelrosario** [comment]
Did you check 2, 3 and 4 on: https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FAQ.md
