### ISSUE TITLE
CrossPushNotification.Current.OnNotificationReceived not fired

### ISSUE THREAD

**Issue by magtimmermans** [CrossGeeks/PushNotificationPlugin#46]
Hi,

I am sending the payload:

  {
    "to" : "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx...",
    "notification" : {
      "body" : "test body",
      "title" : "test Title"
    },
    "data" : {
      "guid" : "234234-232434..."
    }
  }

Status application is closed:
The notification arrived and when I click on the notifcation the app id opened but the event CrossPushNotification.Current.OnNotificationReceived is not triggered? Do I am something wrong here?

I would like to load the complete message from the server using the guid and display it.

On IOS this works fine.

Using version 1.1.5

**Comment by rdelrosario** [comment]
For android you shouldn’t sent notification key. Use data messages instead:

{
"to" : "APA91bHun4MxP5egoKMwt2KZFBaFUH-1RYqx...",
"data" : {
"body" : "test body",
"title" : "test Title",
"guid" : "234234-232434..."
}
}

**Comment by magtimmermans** [comment]
But then this will not show a notification when the app is closed, (not running) ?
