### ISSUE TITLE
Android OnNotificationOpened Not Firing

### ISSUE THREAD

**Issue by edmckee** [CrossGeeks/PushNotificationPlugin#48]
The iOS OnNotificationOpened works but when trying to get to work with android it doesn't work.  I receive messages when the app is in the foreground, and when I click on notifications it opens the app but the OnNotificationOpened isn't called. 
I need this to direct users to a specific page.
Are there any additional settings that are required, or additional code.

`            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("Received");
                NotificationProvider.OnNotificationReceived(JObject.FromObject(p.Data));
            };

            CrossPushNotification.Current.OnNotificationOpened += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("Opened");
                NotificationProvider.OnNotificationOpened(JObject.FromObject(p.Data), p.Identifier);
            };
`

**Comment by rdelrosario** [comment]
How are you sending the payload when android?

**Comment by rdelrosario** [comment]
Also are you calling method ProcessIntent on MainActivity?

**Comment by edmckee** [comment]
This was the problem.  
`        PushNotificationManager.ProcessIntent(this, Intent);`
Thanks for your help
