### ISSUE TITLE
How to test a message sending from Firebase Cloud Messaging (FCM)

### ISSUE THREAD

**Issue by joilsonc** [CrossGeeks/PushNotificationPlugin#51]
Hi, I am new on pushing messaging service. So, despite of everything that you have already published regarding PushNotification Plugin 1.3.0, I was not able to make it works. I have followed line by line. I have NO errors. However I also  do not receive any message from FCM.

I am compiling with Android 8.1 and testing  in  Android Nougat 7.0. Inside Cross Plataform Solution (android / IOS). Everthing seems to be well compiled.

I set CrossPushNotification.Current.RegisterForPushNotifications()  in  OnStart() of my App.cs. Is that fine? 
What exactly is my "default notification channel  ID and Name"? I am use as the tutorial...

if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
                {
                    //Change for your default notification channel id here
                    PushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

                    //Change for your default notification channel name here
                    PushNotificationManager.DefaultNotificationChannelName = "General";
                }

Please, can you give some directions to find out the correct way?

Thank you very much,

regards,
Joilson

**Comment by rdelrosario** [comment]
how are you testing right now? You just could try sending a message from the firebase portal? did you try that and didn't work?

**Comment by joilsonc** [comment]
Hi,
thanks for your promptly reply. Sorry, but I have committed a mistake. I had forgotten to set the GoogleJson in my application. I have made a test from FCM Portal and is working now.
Right now I am gonna try send some messages from my server. Do you have any sample/tip from Xamaring accessing FCM to send messages?

Anyway thanks again,

Joilson

**Comment by rdelrosario** [comment]
You can use https://github.com/tiagomtotti/firebaseNet
