### ISSUE TITLE
Is There Topic Notification using PushNotificationPlugin 1.3.0?

### ISSUE THREAD

**Issue by joilsonc** [CrossGeeks/PushNotificationPlugin#52]
Hello,
if is possible, how can i configure to subscribe for a Topic message from FCM, using CrossPushNotification or something else?

regards,

Joilson

**Comment by rdelrosario** [comment]
If you are using FCM for both platforms ios and android and want topics support then use:

https://github.com/CrossGeeks/FirebasePushNotificationPlugin

**Comment by joilsonc** [comment]
Great, you helped me a lot.
regards,
