### ISSUE TITLE
Do not show notification ui on android when app is in foreground

### ISSUE THREAD

**Issue by vikram-ma** [CrossGeeks/PushNotificationPlugin#54]
Hello, 
I am working on Xamairn.Forms application, where I do not want to show notification ui when app is in foreground on android. (For iOS, it is the default behavior, so I didn't have to do anything). 
I added below code as suggested in one of the issues, but it didn't work.

`CrossPushNotification.Current.OnNotificationReceived += (s, e) =>
{
                if(appIsInforeground)
                    e.Data.Add("silent", true);
};`

Instead I want to show alert dialog when app is in foreground, if user dismisses the alert dialog, then I want to show notification ui

**Comment by rdelrosario** [comment]
How are you setting appIsInforeground?

Where are you updating the value?

**Comment by vikram-ma** [comment]
for testing purpose I set  appIsInforeground to true always, which didn't stop the notification from being shown

**Comment by fpuente70** [comment]
I have the same issue. 
Using the Xamarin sample code provided, creating the corresponding Firebase project on Firebase Console, updated the json file, and compiled. I can send notifications correctly when the app is running but when it is in backgroud or closed it does not seem to be receiving anything. 
Did anyone solved it?

**Comment by rdelrosario** [comment]
This was fixed on latest release
