### ISSUE TITLE
Upgrade Dependencies?

### ISSUE THREAD

**Issue by eduardosantosmoura** [CrossGeeks/PushNotificationPlugin#56]
Hi there
Great work.
I just have a problem right now, your plugin requires "Xamarin.Firebase.Messaging (= 60.1142.0)" so i cannot upgrade the Xamarin.Firebase.Messaging as i would like. Is it possible to have the dependency be      equal or greater than  60.1142.0 instead of just equal?
Best regards

**Comment by rdelrosario** [comment]
Can just be equal, we can upgrade it to a new version but FCM messaging package always depends on a fixed version thats why we have it that way as well.

**Comment by tilutza** [comment]
Using Xamarin.Forms with the latest version of Firebase.Messaging is impossible. This is because the latest Google/Firebase versions depends on a new version that is not compatible with forms.

Do you think it would be possible to use with the old one. 42 ?

**Comment by tilutza** [comment]
The previous constraint used at version 2.1.3 is Xamarin.Firebase.Messaging (>= 42.1021.1)

**Comment by angusbreno** [comment]
We can make the last version of this compatible with the last version of Xamarin Forms (for Android)?

**Comment by mxstudios** [comment]
FYI https://github.com/simonemarra/PushNotificationPlugin fixed the dependency. I forked it and changed the version to 1.3.1 in my repository so I wouldn't get it confused.

Haven't tested my build yet, but it added to project at least....

**Comment by rdelrosario** [comment]
Should be fixed in the latest version:

https://www.nuget.org/packages/Plugin.PushNotification/2.1.11
