### ISSUE TITLE
empty token

### ISSUE THREAD

**Issue by helmishariff** [CrossGeeks/PushNotificationPlugin#57]
I tried IOS sample but I get empty token.

**Comment by rdelrosario** [comment]
Did you initialize?

**Comment by rdelrosario** [comment]
How did you initialize?

**Comment by helmishariff** [comment]
I don't add any code to the sample. In the AppDelegate already have PushNotificationManager.Initialize(options);

**Comment by rdelrosario** [comment]
Are you getting the token on CrossPushNotification.Current.OnTokenRefresh event?

**Comment by rdelrosario** [comment]
Please reopen if still having the issue, will close for now. Should always get the token using the OnTokenRefresh event.
