### ISSUE TITLE
Display notifications from code itself

### ISSUE THREAD

**Issue by dtila** [CrossGeeks/PushNotificationPlugin#58]
I really like your library, but there is something which I am missing: to display notifications from code (schedule notifications let saying)

There is already a library which does that
https://github.com/edsnider/LocalNotificationsPlugin, but I like that here you can customize more here.

There a few improvemenets which I suggest:
- make the notification typed (a class with a few required properties and an Extra)
- allow to display a notification from the PCL 
- allow to schedule notifications (to keep it simple, jut by recognizing by ID)

What do you think ?

**Comment by rdelrosario** [comment]
This plugin is exclusively for handling push notifications. I think is better to keep it push specialized and not a general solution to display notifications.
