### ISSUE TITLE
UnregisterForPushNotifications not working on Android

### ISSUE THREAD

**Issue by oloap86** [CrossGeeks/PushNotificationPlugin#59]
Using Plugin.PushNotification v.1.3.0 when user done a Logout i call UnregisterForPushNotifications  to reset the token and then i call await RegisterForPushNotifications to have a new token (to be ready if the user relog into the app because after logout the user is sended to the login page) the event OnTokenRefresh not fire. In iOS it work correctly but not in Android.

I tryed using both option of token reset on the initialization of PushNotificationManager and in both cases i set false the autoregistration flag. I tryed this conditions under debug and without debug too.

What i'm wrong? I don't receive no errors and the console under debug is clean.

**Comment by asanka-indrajith** [comment]
@oloap86 
Did you able to register using RegisterForPushNotifications method. I'm unable to register as well.

**Comment by oloap86** [comment]
Of course, the registration work correctly

**Comment by rdelrosario** [comment]
Should be fixed on latest version.
