### ISSUE TITLE
Oreo, no notifications while app in the background

### ISSUE THREAD

**Issue by edmckee** [CrossGeeks/PushNotificationPlugin#65]
I have been using the plugin and it's been working well.

We noticed when we tested on Oreo the notification only shows up in OnNotificationReceived when the app is in the foreground  but does not show up in the user notifications when the app is in the background.  One of the app features is to be able to click on a notification and go to a specific page.

This works for other versions on Android.  This is how it's defined, and I'm not sure if the channel information is making it not show.  If that's the case can I set these to notify the user while in the background?  Or is there a value I can include in the payload that Oreo is looking for that will notify the user.

Thanks

`           //Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                PushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

                //Change for your default notification channel name here
                PushNotificationManager.DefaultNotificationChannelName = "General";
            }

            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("MainApplication.Received");
                NotificationProvider.OnNotificationReceived(JObject.FromObject(p.Data));
            };

            CrossPushNotification.Current.OnNotificationOpened += (s, p) =>
            {
                System.Diagnostics.Debug.WriteLine("CrossPushNotification.Current.OnNotificationOpened");
                NotificationProvider.OnNotificationOpened(JObject.FromObject(p.Data), p.Identifier);

            };`

**Comment by jbowmanp1107** [comment]
@edmckee  I am not sure if this will help you, but I found that you need to make sure that you set DefaultNotificationChannelName  and DefaultNotificationChannelId before you call PushNotificationManager.Initialize(this, false). 

I actually wasn't able to get notifications working on Oreo at all until I changed this.

**Comment by edmckee** [comment]
Thanks @jbowmanp1107 I will give that a try.

**Comment by edmckee** [comment]
That Worked!!!  Thanks for your help.
