### ISSUE TITLE
Android Sample: Following sample results in Android Oreo not working

### ISSUE THREAD

**Issue by jbowmanp1107** [CrossGeeks/PushNotificationPlugin#67]
Hi! 

I followed the sample to get this working, and on Android Oreo notifications were not coming in. I tracked down the issue to the default notification channel never have been created because the PushNotificationManager.DefaultNotificationChannelId  and PushNotificationManager.DefaultNotificationChannelName were being set after they were initialized.

See below for the fix. In MainApplication change:

```
public override void OnCreate()
        {
            base.OnCreate();

            //If debug you should reset the token each time.
#if DEBUG
            PushNotificationManager.Initialize(this, true);
#else
            PushNotificationManager.Initialize(this,false);
#endif

            //Set the default notification channel for your app when running Android Oreo
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                PushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

                //Change for your default notification channel name here
                PushNotificationManager.DefaultNotificationChannelName = "General";
            }

            //Handle notification when app is closed here
            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {

            };
        }
```

Should simply be changed to have the default notification channel/Id set first:

```
public override void OnCreate()
        {
            base.OnCreate();


            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O)
            {
                //Change for your default notification channel id here
                PushNotificationManager.DefaultNotificationChannelId = "DefaultChannel";

                //Change for your default notification channel name here
                PushNotificationManager.DefaultNotificationChannelName = "General";
            }

#if DEBUG
            PushNotificationManager.Initialize(this, true);
#else
            PushNotificationManager.Initialize(this,false);
#endif

            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {

            };
        }
```

**Comment by FredBesterwitch** [comment]
There is no difference in your changes, what did you actually change ?

**Comment by jbowmanp1107** [comment]
The order of lines have been changed.

PushNotificationManager.Initialize is now called after DefaultNotificationsName/Id have been set.

Regards,

-Jeff

**Comment by FredBesterwitch** [comment]
Sorry, It's Sunday morning here, had a few big ones last night, my eyes are killing me. :-)
Thanks for the tip
I'm testing the notification with the emulator its not working even after  your changes.
Any tips ? if have added my own google-services.json

**Comment by jbowmanp1107** [comment]
Thinking about it, I never actually used the Emulator at all. Went right to deploying on some test devices. So not sure if there could be an issue there. But to be honest, I simply followed the sample, and it worked (minus what I wrote here of course).

Also double check that the google-services.json build action is set to GoogleServicesJson

**Comment by engmsaleh** [comment]
@jbowmanp1107 I have the same exact issue,  the channel isn't created and I always get an error when trying to post to Null Channel
I have changed the order and now the problem is solved

**Comment by asanka-indrajith** [comment]
@jbowmanp1107: You are a life saver!!! Thank a lot :)
