### ISSUE TITLE
auto registration happens even when I set autoregistration flag false in android

### ISSUE THREAD

**Issue by asanka-indrajith** [CrossGeeks/PushNotificationPlugin#69]
I wanted to use on demand registration. So I set autoregistration flag to false and initialized but I still get a hit at OnTokenRefresh (which shouldn't).

**Comment by codeknox** [comment]
I'm calling `PushNotificationManager.Initialize` with `false` for `autoRegistration` parameter, but I get the same as previous post, it registers for push anyway.

Is it a bug or some other configuration I'm missing?

**Comment by rahulinaction** [comment]
Even I am encountering the same scenario. Is there a workaround to avoid auto registeration everytime

**Comment by rdelrosario** [comment]
Should be fixed on latest version.
