### ISSUE TITLE
PushNotificationManager.Initialize error

### ISSUE THREAD

**Issue by psummo** [CrossGeeks/PushNotificationPlugin#7]
If I comment  line //PushNotificationManager.Initialize(this,true); 
No problem, applicati in start. Without comment crash when PushNotificationManager.Initialize line is read. 
I try with try/catch Block to read type errore in catch clause but nothing. Why do this? I think is Xamarin.Firebase.Id reference the problem

**Comment by rdelrosario** [comment]
Check the FAQ section to fix your issue:
https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/FAQ.md

**Comment by rdelrosario** [comment]
If you keep getting this issue after reading the solution on the FAQ, please open a new issue.
