### ISSUE TITLE
When App is closed, OnNotificationOpened not getting hit.

### ISSUE THREAD

**Issue by asanka-indrajith** [CrossGeeks/PushNotificationPlugin#71]
When App is open, OnNotificationOpened get hit, But if app is closed, when I click the notification it only launches the Main Page.

**Comment by rdelrosario** [comment]
OnNotificationOpened will just trigger when you click on the notification.

OnNotificationReceived will trigger when you receive the notification.

**Comment by asanka-indrajith** [comment]
yes, that's what I meant. when app is closed it doesn't trigger OnNotificationOpened event when I clicked the received notification. I also noticed even native OnNewIntent method also not triggered.

**Comment by rdelrosario** [comment]
Did you set LaunchMode = SingleTop on MainActivity?

**Comment by rdelrosario** [comment]
Which version are you using?

**Comment by Emixam23** [comment]
Hey guys

Just tried on my Iphone, same problem.. :/

Best,

**Comment by asanka-indrajith** [comment]
latest - 1.3.0

**Comment by rdelrosario** [comment]
How are tou sending the payload?

**Comment by Emixam23** [comment]
Hey guys :)

So, it's all about the service that send the payload, look deeper at https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/NotificationActions.md

On Android should use click_action key inside the data payload when sending notification with categories. The value for this key will be the category.

Android Notification Sample Payload:

```
{
    "data": {
        "body" : "hello!",
        "title": "push",
        "click_action":"message"
     },
     
     "priority": "high"
}
```

On iOS should use category key inside the aps payload when sending notification with categories. The value for this key will be the category.

iOS Notification Sample Payload:

```
{
   "aps" : {
      "category" : "message",
      "alert" : {
         "body" : "hello!"
      },
      "badge" : 3
   }
}
```

**Comment by asanka-indrajith** [comment]
payload is something like this.
{
    "data": {
        "type" : "my_custom_value",
        "title" : "Title",
        "message": "message text",
        "id": 22
     }
}
