### ISSUE TITLE
OnNotificationReceived fired instead of OnNotificationOpened

### ISSUE THREAD

**Issue by Emixam23** [CrossGeeks/PushNotificationPlugin#72]
Hey,

I checked your code and everything seems to be alright, however, when I click on the notification on my iPhone, the OnNotificationReceived is raised instead of OnNotificationOpened.

**Version: 1.3.0**

    CrossPushNotification.Current.OnNotificationDeleted += OnNotificationDeleted;
    CrossPushNotification.Current.OnTokenRefresh += OnTokenRefresh;
    CrossPushNotification.Current.OnNotificationError += OnNotificationError;
    CrossPushNotification.Current.OnNotificationOpened += OnNotificationOpened;
    CrossPushNotification.Current.OnNotificationReceived += OnNotificationReceived;

Best,

**Comment by rdelrosario** [comment]
Are you using notifications category actions?

How are you initializing the plugin?

**Comment by Emixam23** [comment]
Hey !

Nop I don't and I watched through other of your opened issues and I don't get the logic of your categories I guess..

Shared code part

        public void Initialize()
        {
            CrossPushNotification.Current.OnNotificationDeleted += OnNotificationDeleted;
            CrossPushNotification.Current.OnTokenRefresh += OnTokenRefresh;
            CrossPushNotification.Current.OnNotificationError += OnNotificationError;
            CrossPushNotification.Current.OnNotificationOpened += OnNotificationOpened;
            CrossPushNotification.Current.OnNotificationReceived += OnNotificationReceived;
        }

iOS:

    public class AppDelegate : UIApplicationDelegate
    {
        #region Push Notifications

        [Export("application:didRegisterForRemoteNotificationsWithDeviceToken:")]
        public override void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            PushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
        }

        [Export("application:didFailToRegisterForRemoteNotificationsWithError:")]
        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            PushNotificationManager.RemoteNotificationRegistrationFailed(error);
        }

        // To receive notifications in foregroung on iOS 9 and below. 
        // To receive notifications in background in any iOS version 
        [Export("application:didReceiveRemoteNotification:fetchCompletionHandler:")]
        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            PushNotificationManager.DidReceiveMessage(userInfo);
        }
        #endregion
     }

**Comment by Emixam23** [comment]
Ok I searched and tried many different things and... It works.. So the category stuff you talked about was the problem. However, I don't understand the point to use this système of category? When you click on the notification, it should call OnNotificationOpened, that would be just logic? Maybe I just didn't understand something so if you have any explanation, I would be really interested to understand :)

Thank you so much btw !

PS: https://github.com/CrossGeeks/PushNotificationPlugin/blob/e438059e9d1a47e86ba82df9c08420137535f6bb/docs/NotificationActions.md
