### ISSUE TITLE
MissingFormatArgumentException when using parameterized notifications

### ISSUE THREAD

**Issue by CR4567** [CrossGeeks/PushNotificationPlugin#73]
Hi,
I get an error when I'm sending a localized push notification with parameters.
I did try lot's of combinations with the loc keys but without any success.

Mainly I send an data object with:
![bildschirmfoto 2018-06-05 um 18 10 48](https://user-images.githubusercontent.com/10132368/40988846-6eda0518-68ec-11e8-9200-a1448ac7d21c.png)

When I receive the message, an error occurs:
![bildschirmfoto 2018-06-05 um 18 16 28](https://user-images.githubusercontent.com/10132368/40988936-b1a9769e-68ec-11e8-8877-87fa3b3e6d06.png)

My strings.xml:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="INACTIVITY">%1$s: Inactivity</string>
...
```

Does anyone know this behavior? is there a mistake in my object or is it a bug in the plugin?

Thanks for your help.

**Comment by CR4567** [comment]
I looked into the code and found the related part:
```
                parameters.TryGetValue("body_loc_args", out  object bodyArgs);
                var localizedBody = getLocalizedString(bodyKey.ToString(), bodyArgs as string[]);
```
So, the parsing of the bodyArgs object to string[] is always null.
It looks like my body_loc_args is not correct but I did try lots of different object types without any success: ["test"] / "test" / {"test"}

What should be the correct?

**Comment by CR4567** [comment]
ok this is only an issue if you're trying to send a data message.
Notification messages are working correctly. 

So, I don't know if this is an issue or the correct behavior. But for in my case I can switch the message type and can continue working with it.

**Comment by rdelrosario** [comment]
Fixed in latest version
