### ISSUE TITLE
Is this library compatible with an API that still uses GCM?

### ISSUE THREAD

**Issue by stefan89** [CrossGeeks/PushNotificationPlugin#74]
Is this library compatible with an API that still uses GCM or do I need to use the old library for that? (https://github.com/rdelrosario/xamarin-plugins/tree/master/PushNotification)

The reason for the question is that I currently don't have time to update the API to support FCM.

**Comment by rdelrosario** [comment]
Not compatible with GCM

**Comment by stefan89** [comment]
@rdelrosario are you sure about that it won't work when the API is still GCM based?

In the Firebase docs I see:
**What happens to my users who don't update their apps?**

As long as users have GCM logic in their apps, they will still receive messages. FCM is backwards compatible with GCM, so even if you don't update your server endpoint now, you can still update your app's logic, and vice versa.

Source: https://firebase.googleblog.com/2018/04/time-to-upgrade-from-gcm-to-fcm.html
