### ISSUE TITLE
Android: bring app to front on click of notification

### ISSUE THREAD

**Issue by gmwilhelm** [CrossGeeks/PushNotificationPlugin#75]
Hello,

i'm playing around with push notifications and the sample app. I have a problem with bringing the app to front when i click on a notification.

When the app is started and sent to the background, clicking on the notification brings it to the front but then pushes the main page again. When i then hit the back button i get back to the first mainpage.

What do i have to do to simply bring the app to front without changing the page?

Regards,
  Dirk

**Comment by rdelrosario** [comment]
Just comment what is doing on the OnNotificationOpened code block.

**Comment by gmwilhelm** [comment]
Hello,

removing the OnNotificationOpen code block didn't work. 

These are the steps to reproduce the behavior:

- app is not running
- send first notification and click on it -> app starts
- send second notification while app is in foreground -> the label in the mainpage will change according to the text in the notification.
- send the app to the background
- send third notification and click on it -> the app will be back in the foreground with the default label text showing
- hit the back button -> now the text from the second notification is shown again
- hit the back button again -> now you are back at the android screen

It doesnt matter if i comment out the OnNotificationOpened block or not, the behavier is still the same.
