### ISSUE TITLE
NotRegistered Error

### ISSUE THREAD

**Issue by hashimks** [CrossGeeks/PushNotificationPlugin#76]
Hello, 
I am using this plugin in a Xamarin Forms app. I am getting the device tokens. But when I try to send a push using say example pushtry, I am getting error saying not registerd. Can you please let me know whether I missed anything?

In MainActivity - OnCreateMethod, under LoadApplication(new App()); I have used

#if DEBUG
            PushNotificationManager.Initialize(this, true);
#else
            PushNotificationManager.Initialize(this,false);
#endif
            PushNotificationManager.ProcessIntent(this, Intent);

Also in App.Xaml.cs in OnStart method I am getting the token

var token = CrossPushNotification.Current.Token;

Can you please help me?

**Comment by hashimks** [comment]
Hello... any updates on this?
I am stuck here

**Comment by rdelrosario** [comment]
Did you try doing the same with the sample app?
