### ISSUE TITLE
IconResource not working in background

### ISSUE THREAD

**Issue by CR4567** [CrossGeeks/PushNotificationPlugin#77]
Hi,

I'm using 
`PushNotificationManager.IconResource = Resource.Drawable.ic_stat_icon;`
to switch the default icon which is a very colorful to a plain black and white icon for push notifications.

In foreground it works correctly but when in background it shows again the default app icon.
I define it in a separate application class and not in the mainactivity.
Also, I tried to switch position with the initializing  of the notification Manager.

Did I miss something?

 ```
 public override void OnCreate()
 {
          base.OnCreate();

        AppContext = this.ApplicationContext;
        PushNotificationManager.Initialize(this, false);
        PushNotificationManager.IconResource = Resource.Drawable.ic_stat_icon;
}
```

**Comment by rdelrosario** [comment]
Hi

Try assigning it on the MainApplication class instead

**Comment by CR4567** [comment]
I tried but didn't help.
As soon as I send the app to the background, the default icon is appearing.

I find a different solution that is working for me. I'm sending the icon tag in my notification body, that's maybe not the cleanest way but it works for the moment.

But I'm still wondering why the IconResource in the app is not working.

**Comment by thomasgalliker** [comment]
I tried this code, but it doesnt show the icon nor the notification color. I only get to see a greyed-out notitification icon. This code is part of OnCreate in MainApplication:
```
PushNotificationManager.Initialize(this, PushNotificationQueue.Current, resetToken, createNotificationChannel, autoRegistration);
PushNotificationManager.IconResource = Resource.Mipmap.ic_notification;
PushNotificationManager.Color = new Android.Graphics.Color(Resource.Color.colorPrimaryBright);
```
I followed all the guidelines on how to create notification icons (alpha+white). The only way I got it to work was by adding following lines to the AndroidManifest, but this somehow make PushNotificationManager.IconResource and PushNotificationManager.Color obsolete.
```
<!-- Set custom default icon. This is used when no icon is set for incoming notification messages. -->
<meta-data
  android:name="com.google.firebase.messaging.default_notification_icon"
  android:resource="@mipmap/ic_notification" />

<!-- Set color used with incoming notification messages. This is used when no color is set for the incoming notification message. -->
<meta-data
  android:name="com.google.firebase.messaging.default_notification_color"
  android:resource="@color/activity_splash_background_color" />
```
