### ISSUE TITLE
Error when trying to install nuget Xamarin.GooglePlayServices.Base 

### ISSUE THREAD

**Issue by niraj-bpsoftware** [CrossGeeks/PushNotificationPlugin#79]
Getting Name not begin with $ character error.
This issue is resolved in xamarin-android.
https://github.com/xamarin/xamarin-android/issues/1698

However not able to update Xamarin.Android.Support.Design as PushNotificationPlugin is 26.02.

Can you please update all the nuget references?

**Comment by rdelrosario** [comment]
Should be fixed in latest version:

https://www.nuget.org/packages/Plugin.PushNotification/2.1.11
