### ISSUE TITLE
Firebase App Not Intialized?

### ISSUE THREAD

**Issue by phillw1994** [CrossGeeks/PushNotificationPlugin#8]
Hi I am getting this error and i have followed your getting started guide. I am using your plugin with XAMARIN FORMS

Java.Lang.IllegalStateException Default Firebase App is not intialized Make sure to call FirebaseApp.InitializeApp(Context) first.

Code Below (Also Google Services Json is in the correct place and set to the correct build action)

MainActivity.cs
protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);

            PushNotificationManager.Initialize(this, true);

            LoadApplication(new App());
            PushNotificationManager.ProcessIntent(Intent);

            //Handle notification when app is closed here
            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                //Toast.MakeText(this, "Message Received", ToastLength.Long);
                //System.Diagnostics.Debug.WriteLine("Received A Message");
            };
        }

Android Manifest
 <receiver
        android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver"
        android:exported="false" />
    <receiver
        android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
        android:exported="true"
        android:permission="com.google.android.c2dm.permission.SEND">
      <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
        <category android:name="com.companyname.Xamarin_Test" />
      </intent-filter>
    </receiver>

Any help would be greatly appreciated

**Comment by rdelrosario** [comment]
Check the FAQ section to fix your issue:
https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/FAQ.md

**Comment by rdelrosario** [comment]
By the way   PushNotificationManager.Initialize(this, true); this goes on an Application class not MainActivity

**Comment by rdelrosario** [comment]
Will close this issue if still have problems just open a new one.
