### ISSUE TITLE
Notification content deserialization with ToString ---> WHY?? 

### ISSUE THREAD

**Issue by rickytribbia** [CrossGeeks/PushNotificationPlugin#80]
We discover that in this version of plugin for some NOT UNDERSTANDABLE reasons there is a deserialization of the Json notification content with system ToString.

First think: thank you for you great job, really: I'm here to make a suggestion of improvement. ;-)

This is a big problem for anyone use custom content inside a notification, but also for whom use values as `title-loc-args` inside `aps.alert` that are not recognized as `List<string>` object, but always as `string`.

Why don't you simply deserialize the notification with a standard serialization/deserialization tool? 
For example with a simple JObject?

I mean that into handler: 

```
CrossPushNotification.Current.OnNotificationOpened += (s, p) =>
{
....
}
```

we can take `p.Data` that is a `IDictionary<string, object>`; ok, great, but ANY object inside of this is a `string`, so any list of strings or a nested dictionary is not recognized as a `List<string` or a `IDictionary<string, object>`. 

I think that is a big limitation of this library, don't you?

Simple example:
an empty `aps.alert.title-loc-args` key (as you concatenate the nested object and I can't understand why) has value `"()"`. 

`"()"` is not deserializable as List<string> in any way.

Another one with a custom object inside a notification: 

```
custom : {
    destination =     {
        section = notifications;
        type = none;
        uri = "<null>";
    };
}
```  

`"custom"` is recognized in `p.Data` as a key, and its value is: 
```
{\n
    destination =     {\n
        section = notifications;\n
        type = none;\n
        uri = "<null>";\n
    };\n
}
``` 
and this is not deserializable too; surely not with `JObject.Parse(value).` because is not Json format. 

Do you agree?

EDIT: 
Investigating this issue I found that it happens ONLY IN IOS.

**Comment by OscarRodriguezEveris** [comment]
Isn't a bug. In iOS parse the json automatically as dictionary.

For fix, 


`        private static string DictionaryToJson(NSDictionary dictionary)
        {
                NSError error;
                var json = NSJsonSerialization.Serialize(dictionary, 
                NSJsonWritingOptions.SortedKeys, out error);
                return json.ToString(NSStringEncoding.UTF8);
        } 
`

Edit the GetParameters method with 

`
                else if (val.Value is NSDictionary)
                {
                    string value = DictionaryToJson((NSDictionary)val.Value);
                    parameters.Add($"{val.Key}", value);
                } 
`

**Comment by joalcego** [comment]
Where is that GetParameters method on? I'm having deserialization issues with custom data

**Comment by joalcego** [comment]
I installed the nuget package and I'm having this issue. What do you suggest to fix this issue in my case? I'm having issues deserializing mobile_center property which value is: _{\n    MessageRecipientId = \"194d29c3-1b20-48c0-9ed3-74726f487740\";\n    MessageRecipientPartitionKey = P134084;\n}_

That's the custom data I sent from my back end.
