### ISSUE TITLE
Does this library work when the API for the app still uses GCM as endpoint?

### ISSUE THREAD

**Issue by stefan89** [CrossGeeks/PushNotificationPlugin#81]
Recently I asked this question here:

**Is this library compatible with an API that still uses GCM?**

The answer I retrieved is:
**Not compatible with GCM**

Now I read the docs of Firebase and I saw that to order of upgrading from GCM to FCM does matter. 
So it is possible to update the app first to FCM and at a later moment you can update the server.

My question now is if you are sure that this library won't work unless you have upgraded the API as well to FCM.

Google docs:
### How do I upgrade?
On a high level, upgrading consists of three main parts: console-side, app-side, and server-side.

In the Firebase console, you'll need to create a new Firebase project using your app's existing Cloud Project ID.
In your app, you'll need to make some code changes. The amount of changes will depend on what features of GCM you currently use, such as topic subscriptions and token generation.
On the server side, you'll need to change the server endpoint from GCM to FCM.
**Keep in mind that you don't have to complete all three parts of the process in one sitting - you can take it at your own pace. For example, you can choose to configure the console today and work on the app code another time. You're also free to update your app's code right now, and tackle the server-side requirements later.**

### What happens to my users who don't update their apps?
As long as users have GCM logic in their apps, they will still receive messages. FCM is backwards compatible with GCM, so even if you don't update your server endpoint now, you can still update your app's logic, and vice versa.

Source: https://firebase.googleblog.com/2018/04/time-to-upgrade-from-gcm-to-fcm.html

**Comment by stefan89** [comment]
Update:

Just tested it to send a message to GCM and it works perfectly using this library.

**Comment by rdelrosario** [comment]
Thanks! @stefan89  for finding this out I actually didn't know. Glad it works on GCM as well
