### ISSUE TITLE
Help -> Erro FirebaseApp initialization unsuccessful

### ISSUE THREAD

**Issue by ivanteles** [CrossGeeks/PushNotificationPlugin#82]
I added the parameters inside the application tag in the maifest file.
I added the internet permissions.
I added the service.json file provided by google, I marked the build action

And I created the MainApplication class as an example.
But when trying to run the application of this error and already for the app.

07-11 16:48:08.237 I/FirebaseInitProvider(14410): FirebaseApp initialization unsuccessful
07-11 16:48:08.237 W/dalvikvm(14410): No implementation found for native Lmd523a6b9646c75a92ddb01fd58267f43a3/MainApplication;.n_onCreate:()V
07-11 16:48:08.237 D/AndroidRuntime(14410): Shutting down VM
07-11 16:48:08.237 W/dalvikvm(14410): threadid=1: thread exiting with uncaught exception (group=0xa4d56b20)
07-11 16:48:08.457 D/Mono    (14410): DllImport searching in: '__Internal' ('(null)').
07-11 16:48:08.457 D/Mono    (14410): Searching for 'java_interop_jnienv_call_void_method_a'.
07-11 16:48:08.457 D/Mono    (14410): Probing 'java_interop_jnienv_call_void_method_a'.
07-11 16:48:08.457 D/Mono    (14410): Found as 'java_interop_jnienv_call_void_method_a'.
Unhandled Exception:

Java.Lang.UnsatisfiedLinkError: Native method not found: md523a6b9646c75a92ddb01fd58267f43a3.MainApplication.n_onCreate:()V

**Comment by ivanteles** [comment]
Solved!

**Comment by galex66** [comment]
What was the problem ? ? ?
