### ISSUE TITLE
Get the device token

### ISSUE THREAD

**Issue by ivanteles** [CrossGeeks/PushNotificationPlugin#83]
When calling the code below in any part of my Shared Project should I not have access to the device token?

```
CrossPushNotification.Current.OnTokenRefresh += (s,p) =>
  {
        System.Diagnostics.Debug.WriteLine($"TOKEN : {p.Token}");
  };
```

Why does it always come empty?

**Comment by ivanteles** [comment]
Can someone help me?

**Comment by ivanteles** [comment]
Solved!

**Comment by 15mgm15** [comment]
@ivanteles Can you share the solution?

**Comment by ivanteles** [comment]
In any part of the shared project code just call: CrossPushNotification.Current.Token
