### ISSUE TITLE
Notification not receiving when app is in foreground ios 10

### ISSUE THREAD

**Issue by Yashshree** [CrossGeeks/PushNotificationPlugin#84]
Notification not receiving when app is in foreground ios 10 , it is working when app is in background.

**Comment by niraj-bpsoftware** [comment]
Any luck @Yashshree ?

**Comment by Panhavorn** [comment]
me too

**Comment by ali-moussa** [comment]
me three

**Comment by michaeldimoudis** [comment]
In ‘PushNotificationManager.cs’ on iOS you have to change ‘public static UNNotificationPresentationOptions CurrentNotificationPresentationOption { get; set; } = UNNotificationPresentationOptions.None;‘ to ‘public static UNNotificationPresentationOptions CurrentNotificationPresentationOption { get; set; } = UNNotificationPresentationOptions.Alert;’
