### ISSUE TITLE
Inconsistent Required Android Version

### ISSUE THREAD

**Issue by ericmclachlan** [CrossGeeks/PushNotificationPlugin#86]
Hey guys

Please could you clarify:

On the main [README.md](https://github.com/CrossGeeks/PushNotificationPlugin), the required Xamarin.Android version is indicated as API 15+.

However, on the [GettingStarted.md](https://github.com/CrossGeeks/PushNotificationPlugin/blob/master/docs/GettingStarted.md), the documentation seems to indicate API 26.
> Must compile against 26+ as plugin is using API 26 specific things.

**Comment by rdelrosario** [comment]
That's the compilation target the other one is the android minimum version. More information here:

http://redth.codes/such-android-api-levels-much-confuse-wow/
