### ISSUE TITLE
IOS Issues 

### ISSUE THREAD

**Issue by niraj-bpsoftware** [CrossGeeks/PushNotificationPlugin#87]
Hi,
I am currently implementing Push Notification in my Xamarin App and have few questions.
First of all, thank you very much for this Plugin. I am able to use it in Android without any issue now however I am facing issues in IOS.
1) Is PushNotificationManager.Initialize(options) in  FinishedLaunching enough? I have checked its code and it doesn't include following code specific to IOS 8.0 which I can find in Xamarin post:
	UIApplication.SharedApplication.RegisterForRemoteNotifications();//present in Xamarin blog post but not in Plugin.PushNotification
2) I am not receiving device token in RegisteredForRemoteNotifications event when I was using PushNotificationManager.Initialize even though I know it may have nothing to do with it so If I replace it 
with Xamarin code it works fine.
3) Since PushNotificationManager.Initialize(options) is Async method, it may have deadlock issue (http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html). I can not make FinishedLaunching async so other 
alternative according to the post is to use ConfigureAwait(false) in all async calls. Any other suggestions?
4) I tried to debug IOS with this plugin but it doesn't. I tried to stop debug and closed the app and open it multiple times but still it doesn't work. How can I debug this?
5) Is there any different setting in debug/release configuration for PushNotification/Plugion that I should do?
6) How can I log information in production environment? Is AppCenterLog.Info a good method? If not what are the alternatives?

Thank you in advance for any help/suggestions.

**Comment by amrkamal1993** [comment]
not working for me for ios i hope there is a solution

**Comment by grammatnMcK** [comment]
me neither.. please help

**Comment by nirajvbhatt** [comment]
ok I am able to get it working now. I made following changes:
1) Instead of using PushNotificationManager.Initialize(options), I used following code:
if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                UNUserNotificationCenter.Current.RequestAuthorization(UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound,
                    (granted, error) =>
                    {
                        if (granted)
                            DispatchQueue.MainQueue.DispatchAsync(UIApplication.SharedApplication.RegisterForRemoteNotifications);
                    });
            }
            else if (UIDevice.CurrentDevice.CheckSystemVersion(8, 0))
            {
                var pushSettings = UIUserNotificationSettings.GetSettingsForTypes(
                    UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound,
                    new NSSet());

                UIApplication.SharedApplication.RegisterUserNotificationSettings(pushSettings);
                UIApplication.SharedApplication.RegisterForRemoteNotifications();
            }
            else
            {
                UIRemoteNotificationType notificationTypes = UIRemoteNotificationType.Alert | UIRemoteNotificationType.Badge | UIRemoteNotificationType.Sound;
                UIApplication.SharedApplication.RegisterForRemoteNotificationTypes(notificationTypes);
            }

2) For IOS10 foreground notification, I created NotificationDelegate:
public class MyNotificationDelegate: UNUserNotificationCenterDelegate
        {
            public override void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification,  Action<UNNotificationPresentationOptions> completionHandler)
            {
                completionHandler(UNNotificationPresentationOptions.Alert);
            }
        }
and used above class delegate in FinishedLaunching as below:
UNUserNotificationCenter.Current.Delegate = new MyNotificationDelegate();

3) Most important, I couldn't receive any push notification during debug. I had to release ios version and installed that on device and it was working fine.

**Comment by amrkamal1993** [comment]
@nirajvbhatt can you post simple ? your code show compilation error in completionHandler

**Comment by nirajvbhatt** [comment]
using System.Collections.Generic;
using CoreBluetooth;
using CoreFoundation;
using Plugin.SecureStorage;
using UserNotifications;
using Plugin.PushNotification;
using ReactiveUI;
using Refractored.XamForms.PullToRefresh.iOS;
using Microsoft.AppCenter;
using Microsoft.AppCenter.Analytics;
using Microsoft.AppCenter.Crashes;

namespace BestHealth.UI.iOS
{
    using System;
    using System.Reactive.Subjects;
    using Foundation;
    using Splat;
    using UI;
    using UIKit;
    [Register("AppDelegate")]
    public partial class AppDelegate : global::Xamarin.Forms.Platform.iOS.FormsApplicationDelegate
    {
        public static AppDelegate Current;
        
        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            FFImageLoading.Forms.Touch.CachedImageRenderer.Init();


            UIApplication.SharedApplication.SetStatusBarStyle(UIStatusBarStyle.LightContent, false);

            Current = this;

                       
            LoadApplication(compositionRoot.ResolveApp());

            // reset our badge
            UIApplication.SharedApplication.ApplicationIconBadgeNumber = 0;

            //PushNotificationManager.Initialize(options);          

            if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                UNUserNotificationCenter.Current.RequestAuthorization(UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound,
                    (granted, error) =>
                    {
                        if (granted)
                            DispatchQueue.MainQueue.DispatchAsync(UIApplication.SharedApplication.RegisterForRemoteNotifications);
                    });
            }
            else if (UIDevice.CurrentDevice.CheckSystemVersion(8, 0))
            {
                var pushSettings = UIUserNotificationSettings.GetSettingsForTypes(
                    UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound,
                    new NSSet());

                UIApplication.SharedApplication.RegisterUserNotificationSettings(pushSettings);
                UIApplication.SharedApplication.RegisterForRemoteNotifications();
            }
            else
            {
                UIRemoteNotificationType notificationTypes = UIRemoteNotificationType.Alert | UIRemoteNotificationType.Badge | UIRemoteNotificationType.Sound;
                UIApplication.SharedApplication.RegisterForRemoteNotificationTypes(notificationTypes);
            }

            UNUserNotificationCenter.Current.Delegate = new MyNotificationDelegate();
            return base.FinishedLaunching(app, options);
            

        
        }
        public class MyNotificationDelegate: UNUserNotificationCenterDelegate
        {
            public override void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification,  Action<UNNotificationPresentationOptions> completionHandler)
            {
                Analytics.TrackEvent("WillPresentNotification",
                    new Dictionary<string, string>
                    {
                        { "DeviceToken", CrossPushNotification.Current.Token }
                    });
                completionHandler(UNNotificationPresentationOptions.Alert);
            }
        }
        


        public override async void RegisteredForRemoteNotifications(UIApplication application, NSData deviceToken)
        {
            PushNotificationManager.DidRegisterRemoteNotifications(deviceToken);
           
        }

        
        public override void FailedToRegisterForRemoteNotifications(UIApplication application, NSError error)
        {
            PushNotificationManager.RemoteNotificationRegistrationFailed(error);
        }

        public override void DidReceiveRemoteNotification(UIApplication application, NSDictionary userInfo, Action<UIBackgroundFetchResult> completionHandler)
        {
            PushNotificationManager.DidReceiveMessage(userInfo);
        }

        

        public override void ReceivedLocalNotification(UIApplication application, UILocalNotification notification)
        {
        }

        public override void ReceivedRemoteNotification(UIApplication application, NSDictionary userInfo)
        {
            AppCenterLog.Info("BHAIOS", "ReceivedRemoteNotification event");
        }


    }
}

**Comment by rdelrosario** [comment]
Should be fixed on latest version.
