### ISSUE TITLE
Conflit version googleplayservice other plugin

### ISSUE THREAD

**Issue by ivanteles** [CrossGeeks/PushNotificationPlugin#90]
Version conflict detected for Xamarin.GooglePlayServices.Basement. Install/reference Xamarin.GooglePlayServices.Basement 60.1142.1 directly to project ColetaSeletiva.Android to resolve this issue. 
 ColetaSeletiva.Android -> Xamarin.Forms.GoogleMaps 3.0.1 -> Xamarin.GooglePlayServices.Maps 60.1142.1 -> Xamarin.GooglePlayServices.Basement (= 60.1142.1) 
 ColetaSeletiva.Android -> Plugin.PushNotification 1.3.0 -> Xamarin.Firebase.Messaging 60.1142.0 -> Xamarin.GooglePlayServices.Basement (= 60.1142.0).	ColetaSeletiva.Android

**Comment by husseinmohkhalil** [comment]
why it is only for 60.1142.0 version?!!

**Comment by rdelrosario** [comment]
Should be fixed in latest version:

https://www.nuget.org/packages/Plugin.PushNotification/2.1.11
