### ISSUE TITLE
Can't install with latest Firebase version

### ISSUE THREAD

**Issue by asgarddesigns** [CrossGeeks/PushNotificationPlugin#91]
It looks like the latest version is hard-coded to Xamarin.Firebase.Messaging version 60.1142.0 however, because play services is now at 60.1142.1, I have to downgrade all play services in order to install this version of firebase.

Is there any reason this is the case? 

Will force installing PushNotificationPlugin alongside 60.1142.1 cause any issues you are aware of? 

Any new release on the near horizon?

**Comment by wammy21** [comment]
this is the same as #56 

Is there a plan to get this sorted out soon? what is the hold up? can't use the latest Xamarin.Forms.Maps either since they update the dependency to 60.1142.1

**Comment by fernandovm** [comment]
Please, update the references.

**Comment by rdelrosario** [comment]
Should be fixed in latest version:

https://www.nuget.org/packages/Plugin.PushNotification/2.1.11
