### ISSUE TITLE
Android FCM Error "not registered"

### ISSUE THREAD

**Issue by CR4567** [CrossGeeks/PushNotificationPlugin#93]
Hi,

we're using this plugin now for quite some time. 
On iOS everything seems to working absolutely fine. But on Android we sometimes have the problem, that our registration ID gets invalidated. Or at least it seems like this.

For some devices when our server sends a message to FCM we get a response that the registration ID is not registered anymore. We checked for the docs about the possibilities but there wasn't an update or something else. And expiration time makes no sense because for one of the users it happens after 3 days. 
There was also no OnTokenRefresh Event. We always send the current ID to the server when the app is opened.

Does anyone have an idea or knows this problem?

What would happen if the app is closed, while the id was invalidated, for whatever reason?
Or could there be a relation to Android Oreo? We're trying to validate, but at the moment it seems that it only happens to recent devices.

**Comment by CR4567** [comment]
Ok after debugging a lot more, I figure out that it's only a problem with receiving the onTokenRefresh Event while the App is closed.
But only in the forms part. 

When I place the onTokenRefresh Listener in the Android Application class it's also working while the app is closed but the forms listener is not triggered. So one solution would be to place the server upload into the android part, but that would be kind of redundant to the forms part.

Isn't it possible to run the forms code while app is closed or backgrounded?

**Comment by rdelrosario** [comment]
When app is closed forms isn't initialized so there's no way to receive the event in forms.
