### ISSUE TITLE
Android exception when notification received with app closed

### ISSUE THREAD

**Issue by andrercarvalho** [CrossGeeks/PushNotificationPlugin#94]
Hi
After following the example guides to implement the plugin i get the error "you MUST call Xamarin.Forms.Init(); prior to using it." when i receive a notification with the app closed.
This problem only occurs in android and if the app is open or in brackground the notification is received without any problem.

Does anyone have an idea or knows this problem?

Thanks in advance

**Comment by rdelrosario** [comment]
What are you doing OnNotificationReceived when app closed? You shouldn't have any Xamarin Forms specific code there.

**Comment by raboon** [comment]
Hi is there any way to receive notification even the app is not ruining. like kind o f background service even the app is close. or i have create my own custom service. if es is it possible to give an simple example.
