### ISSUE TITLE
Cancel Local Notification on Override of OnBuildNotification

### ISSUE THREAD

**Issue by mxstudios** [CrossGeeks/PushNotificationPlugin#95]
Hi,

What would be great is a way to override the OnBuildNotiication to do stuff, but also stop it from actually showing the notification. Our use case calls for some processing of a silent notification so we can show it manually only under some conditions.

Not sure if there is a way to do this currently. It odesn't appear so.

**Comment by rdelrosario** [comment]
The latest version has improvements related to this, methods are now virtual. But also if the application is in foreground won't show notification unless "priority" set to "high" or "max" on the data payload.

**Comment by mxstudios** [comment]
Excellent!
