### ISSUE TITLE
enhancement for custom sound Android O+

### ISSUE THREAD

**Issue by xamplum** [CrossGeeks/PushNotificationPlugin#96]
Hi,

we need custom sounds for each push notification. Unfortunately this doesn't work anymore since Android O. Using notificationChannels, the sound (and other options like importance, sound, lights, vibration...) must me set before creating the channel `notificationManager.CreateNotificationChannel....` . After that it cannot be changed any more. 
Currently only the default sound is played on Android O devices.
Are any further developments planned to make this possible?

So far i've come up with 2 options:
1. set sound for the notificationChannel `null` and call
```
            CrossPushNotification.Current.OnNotificationReceived += (s, p) =>
            {
                if (p.Data.ContainsKey("sound"))
                {
                    MediaPlayer player = MediaPlayer.Create(this, Resources.GetIdentifier(p.Data["sound"].ToString(), "raw", PackageName));
                    player.Start();
                }
            };
```
in my app. (a bit hacky)
Or
2. by working with multiple notificationChannels, one for each configuration. 

Thanks!

**Comment by xamplum** [comment]
Are any developments planned in this respect? I mean to be able to work with multiple channels?

**Comment by rdelrosario** [comment]
Thanks @xamplum
