### ISSUE TITLE
locals notifications do not display "time" when targeting  API is greater than or equal to 26

### ISSUE THREAD

**Issue by SinalyVector** [CrossGeeks/PushNotificationPlugin#97]
NotificationCompat.Builder (context, channelId)
                 .SetShowWhen (true)
                .SetWhen (Java.Lang.JavaSystem.CurrentTimeMillis ());
Although I call the SetShowWhen and SetWhen functions,
Push notifications displayed on System tray doesn't show "timestamp",
when the application is in backgroud and stopped, and when  targeting API is greater than or equal to 26 (Build.VERSION.SdkInt> = Android.OS.BuildVersionCodes.O)

**Comment by AdelaPetrut** [comment]
I have the same problem. How did you manage to resolve it?

**Comment by rdelrosario** [comment]
This should be working on the latest version.
